# coding: utf-8

"""
    Tenant Api

    Tenant Api - v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from edgraph_platform_client.models.tenant_api_tenant_v1_tenant_settings_type_attribute import TenantApiTenantV1TenantSettingsTypeAttribute
from typing import Optional, Set
from typing_extensions import Self

class TenantApiTenantV1TenantSettingTypesListResponse(BaseModel):
    """
    TenantApiTenantV1TenantSettingTypesListResponse
    """ # noqa: E501
    id: Optional[StrictStr] = None
    tenant_id: Optional[StrictStr] = Field(default=None, alias="tenantId")
    code: Optional[StrictStr] = None
    data_type: Optional[StrictStr] = Field(default=None, alias="dataType")
    order: Optional[StrictInt] = None
    hidden: Optional[StrictBool] = None
    html_element: Optional[StrictStr] = Field(default=None, alias="htmlElement")
    label: Optional[StrictStr] = None
    input_type: Optional[StrictStr] = Field(default=None, alias="inputType")
    default_value: Optional[StrictStr] = Field(default=None, alias="defaultValue")
    min_value: Optional[StrictInt] = Field(default=None, alias="minValue")
    max_value: Optional[StrictInt] = Field(default=None, alias="maxValue")
    max_length: Optional[StrictInt] = Field(default=None, alias="maxLength")
    attributes: Optional[List[TenantApiTenantV1TenantSettingsTypeAttribute]] = None
    __properties: ClassVar[List[str]] = ["id", "tenantId", "code", "dataType", "order", "hidden", "htmlElement", "label", "inputType", "defaultValue", "minValue", "maxValue", "maxLength", "attributes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TenantApiTenantV1TenantSettingTypesListResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "attributes",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in attributes (list)
        _items = []
        if self.attributes:
            for _item_attributes in self.attributes:
                if _item_attributes:
                    _items.append(_item_attributes.to_dict())
            _dict['attributes'] = _items
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if tenant_id (nullable) is None
        # and model_fields_set contains the field
        if self.tenant_id is None and "tenant_id" in self.model_fields_set:
            _dict['tenantId'] = None

        # set to None if code (nullable) is None
        # and model_fields_set contains the field
        if self.code is None and "code" in self.model_fields_set:
            _dict['code'] = None

        # set to None if data_type (nullable) is None
        # and model_fields_set contains the field
        if self.data_type is None and "data_type" in self.model_fields_set:
            _dict['dataType'] = None

        # set to None if order (nullable) is None
        # and model_fields_set contains the field
        if self.order is None and "order" in self.model_fields_set:
            _dict['order'] = None

        # set to None if html_element (nullable) is None
        # and model_fields_set contains the field
        if self.html_element is None and "html_element" in self.model_fields_set:
            _dict['htmlElement'] = None

        # set to None if label (nullable) is None
        # and model_fields_set contains the field
        if self.label is None and "label" in self.model_fields_set:
            _dict['label'] = None

        # set to None if input_type (nullable) is None
        # and model_fields_set contains the field
        if self.input_type is None and "input_type" in self.model_fields_set:
            _dict['inputType'] = None

        # set to None if default_value (nullable) is None
        # and model_fields_set contains the field
        if self.default_value is None and "default_value" in self.model_fields_set:
            _dict['defaultValue'] = None

        # set to None if min_value (nullable) is None
        # and model_fields_set contains the field
        if self.min_value is None and "min_value" in self.model_fields_set:
            _dict['minValue'] = None

        # set to None if max_value (nullable) is None
        # and model_fields_set contains the field
        if self.max_value is None and "max_value" in self.model_fields_set:
            _dict['maxValue'] = None

        # set to None if max_length (nullable) is None
        # and model_fields_set contains the field
        if self.max_length is None and "max_length" in self.model_fields_set:
            _dict['maxLength'] = None

        # set to None if attributes (nullable) is None
        # and model_fields_set contains the field
        if self.attributes is None and "attributes" in self.model_fields_set:
            _dict['attributes'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TenantApiTenantV1TenantSettingTypesListResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "tenantId": obj.get("tenantId"),
            "code": obj.get("code"),
            "dataType": obj.get("dataType"),
            "order": obj.get("order"),
            "hidden": obj.get("hidden"),
            "htmlElement": obj.get("htmlElement"),
            "label": obj.get("label"),
            "inputType": obj.get("inputType"),
            "defaultValue": obj.get("defaultValue"),
            "minValue": obj.get("minValue"),
            "maxValue": obj.get("maxValue"),
            "maxLength": obj.get("maxLength"),
            "attributes": [TenantApiTenantV1TenantSettingsTypeAttribute.from_dict(_item) for _item in obj["attributes"]] if obj.get("attributes") is not None else None
        })
        return _obj


