# coding: utf-8

"""
    Tenant Api

    Tenant Api - v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from edgraph_platform_client.models.tenant_api_tenant_v1_license_type import TenantApiTenantV1LicenseType
from edgraph_platform_client.models.tenant_api_tenant_v1_subscription_status import TenantApiTenantV1SubscriptionStatus
from typing import Optional, Set
from typing_extensions import Self

class TenantApiTenantV1SubscriptionProfileResponse(BaseModel):
    """
    TenantApiTenantV1SubscriptionProfileResponse
    """ # noqa: E501
    tenant_id: Optional[StrictStr] = Field(default=None, alias="tenantId")
    subscription_id: Optional[StrictStr] = Field(default=None, alias="subscriptionId")
    application_id: Optional[StrictStr] = Field(default=None, alias="applicationId")
    start_date_time: Optional[StrictStr] = Field(default=None, alias="startDateTime")
    end_date_time: Optional[StrictStr] = Field(default=None, alias="endDateTime")
    actual_end_date_time: Optional[StrictStr] = Field(default=None, alias="actualEndDateTime")
    grace_period: Optional[StrictInt] = Field(default=None, alias="gracePeriod")
    number_of_licenses: Optional[StrictInt] = Field(default=None, alias="numberOfLicenses")
    assigned_licenses: Optional[StrictInt] = Field(default=None, alias="assignedLicenses")
    max_assigned_licenses: Optional[StrictInt] = Field(default=None, alias="maxAssignedLicenses")
    last_max_assigned_licenses_date_time: Optional[StrictStr] = Field(default=None, alias="lastMaxAssignedLicensesDateTime")
    license_type: Optional[TenantApiTenantV1LicenseType] = Field(default=None, alias="licenseType")
    subscription_status: Optional[TenantApiTenantV1SubscriptionStatus] = Field(default=None, alias="subscriptionStatus")
    auto_assign: Optional[StrictBool] = Field(default=None, alias="autoAssign")
    created_by: Optional[StrictStr] = Field(default=None, alias="createdBy")
    created_date_time: Optional[StrictStr] = Field(default=None, alias="createdDateTime")
    last_modified_by: Optional[StrictStr] = Field(default=None, alias="lastModifiedBy")
    last_modified_date_time: Optional[StrictStr] = Field(default=None, alias="lastModifiedDateTime")
    deleted_at: Optional[StrictStr] = Field(default=None, alias="deletedAt")
    __properties: ClassVar[List[str]] = ["tenantId", "subscriptionId", "applicationId", "startDateTime", "endDateTime", "actualEndDateTime", "gracePeriod", "numberOfLicenses", "assignedLicenses", "maxAssignedLicenses", "lastMaxAssignedLicensesDateTime", "licenseType", "subscriptionStatus", "autoAssign", "createdBy", "createdDateTime", "lastModifiedBy", "lastModifiedDateTime", "deletedAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TenantApiTenantV1SubscriptionProfileResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if tenant_id (nullable) is None
        # and model_fields_set contains the field
        if self.tenant_id is None and "tenant_id" in self.model_fields_set:
            _dict['tenantId'] = None

        # set to None if subscription_id (nullable) is None
        # and model_fields_set contains the field
        if self.subscription_id is None and "subscription_id" in self.model_fields_set:
            _dict['subscriptionId'] = None

        # set to None if application_id (nullable) is None
        # and model_fields_set contains the field
        if self.application_id is None and "application_id" in self.model_fields_set:
            _dict['applicationId'] = None

        # set to None if start_date_time (nullable) is None
        # and model_fields_set contains the field
        if self.start_date_time is None and "start_date_time" in self.model_fields_set:
            _dict['startDateTime'] = None

        # set to None if end_date_time (nullable) is None
        # and model_fields_set contains the field
        if self.end_date_time is None and "end_date_time" in self.model_fields_set:
            _dict['endDateTime'] = None

        # set to None if actual_end_date_time (nullable) is None
        # and model_fields_set contains the field
        if self.actual_end_date_time is None and "actual_end_date_time" in self.model_fields_set:
            _dict['actualEndDateTime'] = None

        # set to None if last_max_assigned_licenses_date_time (nullable) is None
        # and model_fields_set contains the field
        if self.last_max_assigned_licenses_date_time is None and "last_max_assigned_licenses_date_time" in self.model_fields_set:
            _dict['lastMaxAssignedLicensesDateTime'] = None

        # set to None if created_by (nullable) is None
        # and model_fields_set contains the field
        if self.created_by is None and "created_by" in self.model_fields_set:
            _dict['createdBy'] = None

        # set to None if created_date_time (nullable) is None
        # and model_fields_set contains the field
        if self.created_date_time is None and "created_date_time" in self.model_fields_set:
            _dict['createdDateTime'] = None

        # set to None if last_modified_by (nullable) is None
        # and model_fields_set contains the field
        if self.last_modified_by is None and "last_modified_by" in self.model_fields_set:
            _dict['lastModifiedBy'] = None

        # set to None if last_modified_date_time (nullable) is None
        # and model_fields_set contains the field
        if self.last_modified_date_time is None and "last_modified_date_time" in self.model_fields_set:
            _dict['lastModifiedDateTime'] = None

        # set to None if deleted_at (nullable) is None
        # and model_fields_set contains the field
        if self.deleted_at is None and "deleted_at" in self.model_fields_set:
            _dict['deletedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TenantApiTenantV1SubscriptionProfileResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tenantId": obj.get("tenantId"),
            "subscriptionId": obj.get("subscriptionId"),
            "applicationId": obj.get("applicationId"),
            "startDateTime": obj.get("startDateTime"),
            "endDateTime": obj.get("endDateTime"),
            "actualEndDateTime": obj.get("actualEndDateTime"),
            "gracePeriod": obj.get("gracePeriod"),
            "numberOfLicenses": obj.get("numberOfLicenses"),
            "assignedLicenses": obj.get("assignedLicenses"),
            "maxAssignedLicenses": obj.get("maxAssignedLicenses"),
            "lastMaxAssignedLicensesDateTime": obj.get("lastMaxAssignedLicensesDateTime"),
            "licenseType": obj.get("licenseType"),
            "subscriptionStatus": obj.get("subscriptionStatus"),
            "autoAssign": obj.get("autoAssign"),
            "createdBy": obj.get("createdBy"),
            "createdDateTime": obj.get("createdDateTime"),
            "lastModifiedBy": obj.get("lastModifiedBy"),
            "lastModifiedDateTime": obj.get("lastModifiedDateTime"),
            "deletedAt": obj.get("deletedAt")
        })
        return _obj


