# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.validations_api_db_environments_v1_azure_synapse_sql_serverless_connection import ValidationsApiDbEnvironmentsV1AzureSynapseSqlServerlessConnection

class TestValidationsApiDbEnvironmentsV1AzureSynapseSqlServerlessConnection(unittest.TestCase):
    """ValidationsApiDbEnvironmentsV1AzureSynapseSqlServerlessConnection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidationsApiDbEnvironmentsV1AzureSynapseSqlServerlessConnection:
        """Test ValidationsApiDbEnvironmentsV1AzureSynapseSqlServerlessConnection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidationsApiDbEnvironmentsV1AzureSynapseSqlServerlessConnection`
        """
        model = ValidationsApiDbEnvironmentsV1AzureSynapseSqlServerlessConnection()
        if include_optional:
            return ValidationsApiDbEnvironmentsV1AzureSynapseSqlServerlessConnection(
                server = '',
                database = '',
                username = '',
                password = ''
            )
        else:
            return ValidationsApiDbEnvironmentsV1AzureSynapseSqlServerlessConnection(
        )
        """

    def testValidationsApiDbEnvironmentsV1AzureSynapseSqlServerlessConnection(self):
        """Test ValidationsApiDbEnvironmentsV1AzureSynapseSqlServerlessConnection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
