# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.api.groups_api import GroupsApi


class TestGroupsApi(unittest.TestCase):
    """GroupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GroupsApi()

    def tearDown(self) -> None:
        pass

    def test_add_users_to_group_async(self) -> None:
        """Test case for add_users_to_group_async

        Adds users to group.
        """
        pass

    def test_create_analytics_power_bi_group(self) -> None:
        """Test case for create_analytics_power_bi_group

        Creates a group.
        """
        pass

    def test_delete_analytics_power_bi_group(self) -> None:
        """Test case for delete_analytics_power_bi_group

        Deletes a group.
        """
        pass

    def test_get_analytics_power_bi_group_users(self) -> None:
        """Test case for get_analytics_power_bi_group_users

        Retrieves all users for a specific group.
        """
        pass

    def test_get_groups_async(self) -> None:
        """Test case for get_groups_async

        Retrieves a list of groups.
        """
        pass


if __name__ == '__main__':
    unittest.main()
