# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.ed_graph_http_aggregators_tenant_api_services_observations_set_role_configuration_request import EdGraphHttpAggregatorsTenantApiServicesObservationsSetRoleConfigurationRequest

class TestEdGraphHttpAggregatorsTenantApiServicesObservationsSetRoleConfigurationRequest(unittest.TestCase):
    """EdGraphHttpAggregatorsTenantApiServicesObservationsSetRoleConfigurationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EdGraphHttpAggregatorsTenantApiServicesObservationsSetRoleConfigurationRequest:
        """Test EdGraphHttpAggregatorsTenantApiServicesObservationsSetRoleConfigurationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EdGraphHttpAggregatorsTenantApiServicesObservationsSetRoleConfigurationRequest`
        """
        model = EdGraphHttpAggregatorsTenantApiServicesObservationsSetRoleConfigurationRequest()
        if include_optional:
            return EdGraphHttpAggregatorsTenantApiServicesObservationsSetRoleConfigurationRequest(
                tenant_id = '',
                role = '',
                assigned_persona_identifiers = [
                    ''
                    ]
            )
        else:
            return EdGraphHttpAggregatorsTenantApiServicesObservationsSetRoleConfigurationRequest(
        )
        """

    def testEdGraphHttpAggregatorsTenantApiServicesObservationsSetRoleConfigurationRequest(self):
        """Test EdGraphHttpAggregatorsTenantApiServicesObservationsSetRoleConfigurationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
