# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.form_api_forms_v1_update_full_form_request import FormApiFormsV1UpdateFullFormRequest

class TestFormApiFormsV1UpdateFullFormRequest(unittest.TestCase):
    """FormApiFormsV1UpdateFullFormRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FormApiFormsV1UpdateFullFormRequest:
        """Test FormApiFormsV1UpdateFullFormRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FormApiFormsV1UpdateFullFormRequest`
        """
        model = FormApiFormsV1UpdateFullFormRequest()
        if include_optional:
            return FormApiFormsV1UpdateFullFormRequest(
                id = '',
                name = '',
                description = '',
                source = 'Unknown',
                version = '',
                anonymous = True,
                tenant_id = '',
                status = 'Unknown',
                sections = [
                    edgraph_platform_client.models.form_api/forms/v1/update_full_section_request.FormApi.Forms.V1.UpdateFullSectionRequest(
                        id = '', 
                        title = '', 
                        description = '', 
                        questions = [
                            edgraph_platform_client.models.form_api/forms/v1/update_full_question_request.FormApi.Forms.V1.UpdateFullQuestionRequest(
                                id = '', 
                                title = '', 
                                description = '', 
                                type = 'Unknown', 
                                required = True, 
                                default_value = '', 
                                validation = edgraph_platform_client.models.form_api/forms/v1/update_full_question_validation_request.FormApi.Forms.V1.UpdateFullQuestionValidationRequest(
                                    min_length = 56, 
                                    max_length = 56, ), 
                                options = [
                                    ''
                                    ], 
                                order = 56, 
                                component = '', )
                            ], 
                        order = 56, )
                    ]
            )
        else:
            return FormApiFormsV1UpdateFullFormRequest(
        )
        """

    def testFormApiFormsV1UpdateFullFormRequest(self):
        """Test FormApiFormsV1UpdateFullFormRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
