# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.api.analytics_connectors_api import AnalyticsConnectorsApi


class TestAnalyticsConnectorsApi(unittest.TestCase):
    """AnalyticsConnectorsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AnalyticsConnectorsApi()

    def tearDown(self) -> None:
        pass

    def test_create_connector(self) -> None:
        """Test case for create_connector

        Creates a new connector
        """
        pass

    def test_delete_connector(self) -> None:
        """Test case for delete_connector

        Deletes a connector by Id
        """
        pass

    def test_get_adls_gen2_connector_by_id(self) -> None:
        """Test case for get_adls_gen2_connector_by_id

        Retrieves a connector profile by Id
        """
        pass

    def test_get_paginated_connectors(self) -> None:
        """Test case for get_paginated_connectors

        Retrieves paginated connectors
        """
        pass

    def test_update_connector(self) -> None:
        """Test case for update_connector

        Updates a connector by Id
        """
        pass


if __name__ == '__main__':
    unittest.main()
