# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.settings_api_user_settings_v1_create_user_setting_response import SettingsApiUserSettingsV1CreateUserSettingResponse

class TestSettingsApiUserSettingsV1CreateUserSettingResponse(unittest.TestCase):
    """SettingsApiUserSettingsV1CreateUserSettingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SettingsApiUserSettingsV1CreateUserSettingResponse:
        """Test SettingsApiUserSettingsV1CreateUserSettingResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SettingsApiUserSettingsV1CreateUserSettingResponse`
        """
        model = SettingsApiUserSettingsV1CreateUserSettingResponse()
        if include_optional:
            return SettingsApiUserSettingsV1CreateUserSettingResponse(
                setting_id = ''
            )
        else:
            return SettingsApiUserSettingsV1CreateUserSettingResponse(
        )
        """

    def testSettingsApiUserSettingsV1CreateUserSettingResponse(self):
        """Test SettingsApiUserSettingsV1CreateUserSettingResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
