# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.identity_api_instructional_insights_v1_update_instructional_insights_security_sync_job_request import IdentityApiInstructionalInsightsV1UpdateInstructionalInsightsSecuritySyncJobRequest

class TestIdentityApiInstructionalInsightsV1UpdateInstructionalInsightsSecuritySyncJobRequest(unittest.TestCase):
    """IdentityApiInstructionalInsightsV1UpdateInstructionalInsightsSecuritySyncJobRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IdentityApiInstructionalInsightsV1UpdateInstructionalInsightsSecuritySyncJobRequest:
        """Test IdentityApiInstructionalInsightsV1UpdateInstructionalInsightsSecuritySyncJobRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IdentityApiInstructionalInsightsV1UpdateInstructionalInsightsSecuritySyncJobRequest`
        """
        model = IdentityApiInstructionalInsightsV1UpdateInstructionalInsightsSecuritySyncJobRequest()
        if include_optional:
            return IdentityApiInstructionalInsightsV1UpdateInstructionalInsightsSecuritySyncJobRequest(
                job_id = '',
                tenant_id = '',
                name = '',
                input = edgraph_platform_client.models.identity_api/instructional_insights/v1/instructional_insights_security_sync_job_input_message.IdentityApi.InstructionalInsights.V1.InstructionalInsightsSecuritySyncJobInputMessage(
                    tenant = '', 
                    page_size = 56, 
                    order_by = '', 
                    filter = '', 
                    load_batch_size = 56, 
                    load_batch_throttle = '', ),
                schedule = edgraph_platform_client.models.identity_api/instructional_insights/v1/schedule_message.IdentityApi.InstructionalInsights.V1.ScheduleMessage(
                    enabled = True, 
                    begin_date = '', 
                    end_date = '', 
                    cron_expression = '', 
                    time_zone = '', ),
                retry_policy = edgraph_platform_client.models.identity_api/instructional_insights/v1/retry_policy_message.IdentityApi.InstructionalInsights.V1.RetryPolicyMessage(
                    backoff_multiplier = 1.337, 
                    initial_delay = '', 
                    max_attempts = 56, 
                    max_backoff = '', 
                    timeout = '', ),
                callback_notifications = [
                    edgraph_platform_client.models.identity_api/instructional_insights/v1/callback_notification_message.IdentityApi.InstructionalInsights.V1.CallbackNotificationMessage(
                        notification_type = '', 
                        value = '', )
                    ]
            )
        else:
            return IdentityApiInstructionalInsightsV1UpdateInstructionalInsightsSecuritySyncJobRequest(
        )
        """

    def testIdentityApiInstructionalInsightsV1UpdateInstructionalInsightsSecuritySyncJobRequest(self):
        """Test IdentityApiInstructionalInsightsV1UpdateInstructionalInsightsSecuritySyncJobRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
