# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.ed_graph_http_aggregators_tenant_api_services_observations_get_application_settings_response import EdGraphHttpAggregatorsTenantApiServicesObservationsGetApplicationSettingsResponse

class TestEdGraphHttpAggregatorsTenantApiServicesObservationsGetApplicationSettingsResponse(unittest.TestCase):
    """EdGraphHttpAggregatorsTenantApiServicesObservationsGetApplicationSettingsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EdGraphHttpAggregatorsTenantApiServicesObservationsGetApplicationSettingsResponse:
        """Test EdGraphHttpAggregatorsTenantApiServicesObservationsGetApplicationSettingsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EdGraphHttpAggregatorsTenantApiServicesObservationsGetApplicationSettingsResponse`
        """
        model = EdGraphHttpAggregatorsTenantApiServicesObservationsGetApplicationSettingsResponse()
        if include_optional:
            return EdGraphHttpAggregatorsTenantApiServicesObservationsGetApplicationSettingsResponse(
                tenant_id = '',
                forms = [
                    edgraph_platform_client.models.ed_graph/http_aggregators/tenant/api/services/observations/form_configuration_response.EdGraph.HttpAggregators.Tenant.Api.Services.Observations.FormConfigurationResponse(
                        form_id = '', 
                        versions = [
                            edgraph_platform_client.models.ed_graph/http_aggregators/tenant/api/services/observations/form_version_configuration_response.EdGraph.HttpAggregators.Tenant.Api.Services.Observations.FormVersionConfigurationResponse(
                                version = '', 
                                active_starting_date = '', 
                                active_until_date = '', )
                            ], )
                    ]
            )
        else:
            return EdGraphHttpAggregatorsTenantApiServicesObservationsGetApplicationSettingsResponse(
        )
        """

    def testEdGraphHttpAggregatorsTenantApiServicesObservationsGetApplicationSettingsResponse(self):
        """Test EdGraphHttpAggregatorsTenantApiServicesObservationsGetApplicationSettingsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
