# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.tenant_api_integrations_v1_create_integration_type_response import TenantApiIntegrationsV1CreateIntegrationTypeResponse

class TestTenantApiIntegrationsV1CreateIntegrationTypeResponse(unittest.TestCase):
    """TenantApiIntegrationsV1CreateIntegrationTypeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantApiIntegrationsV1CreateIntegrationTypeResponse:
        """Test TenantApiIntegrationsV1CreateIntegrationTypeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantApiIntegrationsV1CreateIntegrationTypeResponse`
        """
        model = TenantApiIntegrationsV1CreateIntegrationTypeResponse()
        if include_optional:
            return TenantApiIntegrationsV1CreateIntegrationTypeResponse(
                id = ''
            )
        else:
            return TenantApiIntegrationsV1CreateIntegrationTypeResponse(
        )
        """

    def testTenantApiIntegrationsV1CreateIntegrationTypeResponse(self):
        """Test TenantApiIntegrationsV1CreateIntegrationTypeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
