# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.ed_graph_http_aggregators_tenant_api_services_observations_user_sync_job_response import EdGraphHttpAggregatorsTenantApiServicesObservationsUserSyncJobResponse

class TestEdGraphHttpAggregatorsTenantApiServicesObservationsUserSyncJobResponse(unittest.TestCase):
    """EdGraphHttpAggregatorsTenantApiServicesObservationsUserSyncJobResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EdGraphHttpAggregatorsTenantApiServicesObservationsUserSyncJobResponse:
        """Test EdGraphHttpAggregatorsTenantApiServicesObservationsUserSyncJobResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EdGraphHttpAggregatorsTenantApiServicesObservationsUserSyncJobResponse`
        """
        model = EdGraphHttpAggregatorsTenantApiServicesObservationsUserSyncJobResponse()
        if include_optional:
            return EdGraphHttpAggregatorsTenantApiServicesObservationsUserSyncJobResponse(
                tenant_id = '',
                mode = 'Unknown',
                provider = 'Unknown',
                connection_id = '',
                job_id = '',
                client_id = '',
                client_secret = '',
                base_url = '',
                authentication_url = '',
                resources_url = '',
                enabled = True,
                ed_fi_instance_id = '',
                use_ssa_instead_of_seoaa = edgraph_platform_client.models.data_sync_api/ed_fi_roster_sync/v1/use_ssa_instead_of_seoaa_options.DataSyncApi.EdFiRosterSync.V1.Use_SSA_InsteadOf_SEOAA_Options(
                    enabled = True, 
                    ignored_staff_classification_descriptors = [
                        ''
                        ], 
                    searched_classroom_position_descriptor = '', 
                    assigned_staff_classification_descriptor = '', ),
                import_section_and_course_data = True,
                use_staff_ed_org_contact_association_for_emails = True,
                ignore_end_dates = True,
                executions_list = [
                    edgraph_platform_client.models.data_sync_api/job_execution/v1/job_execution_list_response.DataSyncApi.JobExecution.V1.JobExecutionListResponse(
                        tenant_id = '', 
                        job_id = '', 
                        application_id = '', 
                        job_execution_id = '', 
                        job_execution_status = 'Unknown', 
                        job_execution_start_date_time = '', 
                        job_execution_end_date_time = '', 
                        child_jobs = [
                            edgraph_platform_client.models.data_sync_api/job_execution/v1/child_job.DataSyncApi.JobExecution.V1.ChildJob(
                                job_id = '', 
                                job_execution_id = '', 
                                child_job_id = '', 
                                child_job_name = '', 
                                job_execution_start_date_time = '', 
                                job_execution_end_date_time = '', 
                                metrics = [
                                    edgraph_platform_client.models.data_sync_api/job_execution/v1/metric.DataSyncApi.JobExecution.V1.Metric(
                                        entity = '', 
                                        processed = 56, 
                                        success = 56, 
                                        errors = 56, )
                                    ], )
                            ], 
                        metrics = [
                            edgraph_platform_client.models.data_sync_api/job_execution/v1/metric.DataSyncApi.JobExecution.V1.Metric(
                                entity = '', 
                                processed = 56, 
                                success = 56, 
                                errors = 56, )
                            ], )
                    ]
            )
        else:
            return EdGraphHttpAggregatorsTenantApiServicesObservationsUserSyncJobResponse(
        )
        """

    def testEdGraphHttpAggregatorsTenantApiServicesObservationsUserSyncJobResponse(self):
        """Test EdGraphHttpAggregatorsTenantApiServicesObservationsUserSyncJobResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
