# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.ed_graph_http_aggregators_tenant_api_controllers_v1_view_models_responses_enrollment_admin_feeder_pattern_dto_paginated_items_view_model import EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminFeederPatternDtoPaginatedItemsViewModel

class TestEdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminFeederPatternDtoPaginatedItemsViewModel(unittest.TestCase):
    """EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminFeederPatternDtoPaginatedItemsViewModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminFeederPatternDtoPaginatedItemsViewModel:
        """Test EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminFeederPatternDtoPaginatedItemsViewModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminFeederPatternDtoPaginatedItemsViewModel`
        """
        model = EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminFeederPatternDtoPaginatedItemsViewModel()
        if include_optional:
            return EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminFeederPatternDtoPaginatedItemsViewModel(
                page_index = 56,
                page_size = 56,
                count = 56,
                data = [
                    edgraph_platform_client.models.ed_graph/http_aggregators/tenant/api/controllers/v1/view_models/responses/enrollment_admin/feeder_pattern_dto.EdGraph.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Responses.EnrollmentAdmin.FeederPatternDto(
                        id = '', 
                        tenant_id = '', 
                        type = '', 
                        geometry = edgraph_platform_client.models.ed_graph/http_aggregators/tenant/api/controllers/v1/view_models/responses/enrollment_admin/polygon_dto.EdGraph.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Responses.EnrollmentAdmin.PolygonDto(
                            rings = [
                                edgraph_platform_client.models.ed_graph/http_aggregators/tenant/api/controllers/v1/view_models/responses/enrollment_admin/linear_ring_dto.EdGraph.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Responses.EnrollmentAdmin.LinearRingDto(
                                    positions = [
                                        edgraph_platform_client.models.ed_graph/http_aggregators/tenant/api/controllers/v1/view_models/responses/enrollment_admin/geo_position_dto.EdGraph.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Responses.EnrollmentAdmin.GeoPositionDto(
                                            longitude = 1.337, 
                                            latitude = 1.337, )
                                        ], )
                                ], ), 
                        properties = edgraph_platform_client.models.ed_graph/http_aggregators/tenant/api/controllers/v1/view_models/responses/enrollment_admin/feeder_pattern_properties_dto.EdGraph.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Responses.EnrollmentAdmin.FeederPatternPropertiesDto(
                            fid = 56, 
                            high_school = '', 
                            elementary = '', 
                            middle_school = '', 
                            hs_num = 56, 
                            es_num = 56, 
                            ms_num = 56, 
                            hs_data_page = '', 
                            es_data_page = '', 
                            ms_data_page = '', 
                            feeder_pattern = '', 
                            color = '', ), 
                        created_by = '', 
                        created_date_time = '', 
                        last_modified_by = '', 
                        last_modified_date_time = '', 
                        is_deleted = True, )
                    ]
            )
        else:
            return EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminFeederPatternDtoPaginatedItemsViewModel(
        )
        """

    def testEdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminFeederPatternDtoPaginatedItemsViewModel(self):
        """Test EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminFeederPatternDtoPaginatedItemsViewModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
