# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.identity_api_user_v1_license_status import IdentityApiUserV1LicenseStatus

class TestIdentityApiUserV1LicenseStatus(unittest.TestCase):
    """IdentityApiUserV1LicenseStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdentityApiUserV1LicenseStatus(self):
        """Test IdentityApiUserV1LicenseStatus"""
        # inst = IdentityApiUserV1LicenseStatus()

if __name__ == '__main__':
    unittest.main()
