# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.form_api_questions_v1_question_created_response import FormApiQuestionsV1QuestionCreatedResponse

class TestFormApiQuestionsV1QuestionCreatedResponse(unittest.TestCase):
    """FormApiQuestionsV1QuestionCreatedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FormApiQuestionsV1QuestionCreatedResponse:
        """Test FormApiQuestionsV1QuestionCreatedResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FormApiQuestionsV1QuestionCreatedResponse`
        """
        model = FormApiQuestionsV1QuestionCreatedResponse()
        if include_optional:
            return FormApiQuestionsV1QuestionCreatedResponse(
                id = '',
                form_id = '',
                section_id = '',
                tenant_id = ''
            )
        else:
            return FormApiQuestionsV1QuestionCreatedResponse(
        )
        """

    def testFormApiQuestionsV1QuestionCreatedResponse(self):
        """Test FormApiQuestionsV1QuestionCreatedResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
