# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.ed_graph_http_aggregators_tenant_api_controllers_v2_responses_user_license import EdGraphHttpAggregatorsTenantApiControllersV2ResponsesUserLicense

class TestEdGraphHttpAggregatorsTenantApiControllersV2ResponsesUserLicense(unittest.TestCase):
    """EdGraphHttpAggregatorsTenantApiControllersV2ResponsesUserLicense unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EdGraphHttpAggregatorsTenantApiControllersV2ResponsesUserLicense:
        """Test EdGraphHttpAggregatorsTenantApiControllersV2ResponsesUserLicense
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EdGraphHttpAggregatorsTenantApiControllersV2ResponsesUserLicense`
        """
        model = EdGraphHttpAggregatorsTenantApiControllersV2ResponsesUserLicense()
        if include_optional:
            return EdGraphHttpAggregatorsTenantApiControllersV2ResponsesUserLicense(
                application_id = '',
                application_name = '',
                role = edgraph_platform_client.models.ed_graph/http_aggregators/tenant/api/controllers/v2/responses/user_license_role.EdGraph.HttpAggregators.Tenant.Api.Controllers.v2.Responses.UserLicenseRole(
                    role_name = '', 
                    display_name = '', ),
                license_status = '',
                license_source = '',
                education_organization_id = 56,
                education_organization_source = '',
                staff_classification = ''
            )
        else:
            return EdGraphHttpAggregatorsTenantApiControllersV2ResponsesUserLicense(
        )
        """

    def testEdGraphHttpAggregatorsTenantApiControllersV2ResponsesUserLicense(self):
        """Test EdGraphHttpAggregatorsTenantApiControllersV2ResponsesUserLicense"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
