# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.ims_admin_api_v1_clients_add_client_secret_request import IMSAdminApiV1ClientsAddClientSecretRequest

class TestIMSAdminApiV1ClientsAddClientSecretRequest(unittest.TestCase):
    """IMSAdminApiV1ClientsAddClientSecretRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IMSAdminApiV1ClientsAddClientSecretRequest:
        """Test IMSAdminApiV1ClientsAddClientSecretRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IMSAdminApiV1ClientsAddClientSecretRequest`
        """
        model = IMSAdminApiV1ClientsAddClientSecretRequest()
        if include_optional:
            return IMSAdminApiV1ClientsAddClientSecretRequest(
                tenant_id = '',
                application_id = '',
                client_id = '',
                expiration = '',
                description = ''
            )
        else:
            return IMSAdminApiV1ClientsAddClientSecretRequest(
        )
        """

    def testIMSAdminApiV1ClientsAddClientSecretRequest(self):
        """Test IMSAdminApiV1ClientsAddClientSecretRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
