# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.api.changes_logs_api import ChangesLogsApi


class TestChangesLogsApi(unittest.TestCase):
    """ChangesLogsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ChangesLogsApi()

    def tearDown(self) -> None:
        pass

    def test_get_all_changes_async(self) -> None:
        """Test case for get_all_changes_async

        """
        pass


if __name__ == '__main__':
    unittest.main()
