# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.settings_api_tenant_settings_v1_search_tenant_settings_response import SettingsApiTenantSettingsV1SearchTenantSettingsResponse

class TestSettingsApiTenantSettingsV1SearchTenantSettingsResponse(unittest.TestCase):
    """SettingsApiTenantSettingsV1SearchTenantSettingsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SettingsApiTenantSettingsV1SearchTenantSettingsResponse:
        """Test SettingsApiTenantSettingsV1SearchTenantSettingsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SettingsApiTenantSettingsV1SearchTenantSettingsResponse`
        """
        model = SettingsApiTenantSettingsV1SearchTenantSettingsResponse()
        if include_optional:
            return SettingsApiTenantSettingsV1SearchTenantSettingsResponse(
                page_index = 56,
                page_size = 56,
                count = 56,
                data = [
                    edgraph_platform_client.models.settings_api/tenant_settings/v1/tenant_setting_message.SettingsApi.TenantSettings.V1.TenantSettingMessage(
                        id = '', 
                        setting_type_id = '', 
                        application_id = '', 
                        schema_version = '', 
                        value = edgraph_platform_client.models.google/protobuf/well_known_types/value.Google.Protobuf.WellKnownTypes.Value(
                            null_value = 'NullValue', 
                            has_null_value = True, 
                            number_value = 1.337, 
                            has_number_value = True, 
                            string_value = '', 
                            has_string_value = True, 
                            bool_value = True, 
                            has_bool_value = True, 
                            struct_value = edgraph_platform_client.models.google/protobuf/well_known_types/struct.Google.Protobuf.WellKnownTypes.Struct(
                                fields = {
                                    'key' : edgraph_platform_client.models.google/protobuf/well_known_types/value.Google.Protobuf.WellKnownTypes.Value(
                                        has_null_value = True, 
                                        number_value = 1.337, 
                                        has_number_value = True, 
                                        string_value = '', 
                                        has_string_value = True, 
                                        bool_value = True, 
                                        has_bool_value = True, 
                                        list_value = edgraph_platform_client.models.google/protobuf/well_known_types/list_value.Google.Protobuf.WellKnownTypes.ListValue(
                                            values = [
                                                
                                                ], ), 
                                        kind_case = None, )
                                    }, ), 
                            list_value = edgraph_platform_client.models.google/protobuf/well_known_types/list_value.Google.Protobuf.WellKnownTypes.ListValue(), 
                            kind_case = None, ), 
                        created_by = '', 
                        created_date_time = '', 
                        last_modified_by = '', 
                        last_modified_date_time = '', 
                        provider = '', 
                        code = '', )
                    ]
            )
        else:
            return SettingsApiTenantSettingsV1SearchTenantSettingsResponse(
        )
        """

    def testSettingsApiTenantSettingsV1SearchTenantSettingsResponse(self):
        """Test SettingsApiTenantSettingsV1SearchTenantSettingsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
