# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.validations_api_jobs_v1_child_job import ValidationsApiJobsV1ChildJob

class TestValidationsApiJobsV1ChildJob(unittest.TestCase):
    """ValidationsApiJobsV1ChildJob unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidationsApiJobsV1ChildJob:
        """Test ValidationsApiJobsV1ChildJob
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidationsApiJobsV1ChildJob`
        """
        model = ValidationsApiJobsV1ChildJob()
        if include_optional:
            return ValidationsApiJobsV1ChildJob(
                job_id = '',
                job_execution_id = '',
                child_job_id = '',
                child_job_name = '',
                job_execution_status = 'Unknown',
                job_execution_start_date_time = '',
                job_execution_end_date_time = '',
                metrics = [
                    edgraph_platform_client.models.validations_api/jobs/v1/metric.ValidationsApi.Jobs.V1.Metric(
                        entity = '', 
                        processed = 56, 
                        success = 56, 
                        errors = 56, )
                    ]
            )
        else:
            return ValidationsApiJobsV1ChildJob(
        )
        """

    def testValidationsApiJobsV1ChildJob(self):
        """Test ValidationsApiJobsV1ChildJob"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
