# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.edfi_admin_api_edfi_admin_v1_sync_local_education_agency_request import EdfiAdminApiEdfiAdminV1SyncLocalEducationAgencyRequest

class TestEdfiAdminApiEdfiAdminV1SyncLocalEducationAgencyRequest(unittest.TestCase):
    """EdfiAdminApiEdfiAdminV1SyncLocalEducationAgencyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EdfiAdminApiEdfiAdminV1SyncLocalEducationAgencyRequest:
        """Test EdfiAdminApiEdfiAdminV1SyncLocalEducationAgencyRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EdfiAdminApiEdfiAdminV1SyncLocalEducationAgencyRequest`
        """
        model = EdfiAdminApiEdfiAdminV1SyncLocalEducationAgencyRequest()
        if include_optional:
            return EdfiAdminApiEdfiAdminV1SyncLocalEducationAgencyRequest(
                tenant_id = '',
                instance_id = '',
                year = 56,
                ed_org_id = 56,
                ed_org_guid = '',
                entries = [
                    edgraph_platform_client.models.edfi_admin_api/edfi_admin/v1/sync_entry.EdfiAdminApi.EdfiAdmin.V1.SyncEntry(
                        tenant_id = '', 
                        instances = [
                            ''
                            ], )
                    ],
                assign_to_existing_applications = True
            )
        else:
            return EdfiAdminApiEdfiAdminV1SyncLocalEducationAgencyRequest(
        )
        """

    def testEdfiAdminApiEdfiAdminV1SyncLocalEducationAgencyRequest(self):
        """Test EdfiAdminApiEdfiAdminV1SyncLocalEducationAgencyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
