# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.ims_admin_api_v1_clients_regenerate_client_secret_request import IMSAdminApiV1ClientsRegenerateClientSecretRequest

class TestIMSAdminApiV1ClientsRegenerateClientSecretRequest(unittest.TestCase):
    """IMSAdminApiV1ClientsRegenerateClientSecretRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IMSAdminApiV1ClientsRegenerateClientSecretRequest:
        """Test IMSAdminApiV1ClientsRegenerateClientSecretRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IMSAdminApiV1ClientsRegenerateClientSecretRequest`
        """
        model = IMSAdminApiV1ClientsRegenerateClientSecretRequest()
        if include_optional:
            return IMSAdminApiV1ClientsRegenerateClientSecretRequest(
                tenant_id = '',
                client_id = '',
                instance_id = '',
                secret_expiration_date_time = ''
            )
        else:
            return IMSAdminApiV1ClientsRegenerateClientSecretRequest(
        )
        """

    def testIMSAdminApiV1ClientsRegenerateClientSecretRequest(self):
        """Test IMSAdminApiV1ClientsRegenerateClientSecretRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
