# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.ed_graph_services_state_reporting_v1_set_submission_status_request import EdGraphServicesStateReportingV1SetSubmissionStatusRequest

class TestEdGraphServicesStateReportingV1SetSubmissionStatusRequest(unittest.TestCase):
    """EdGraphServicesStateReportingV1SetSubmissionStatusRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EdGraphServicesStateReportingV1SetSubmissionStatusRequest:
        """Test EdGraphServicesStateReportingV1SetSubmissionStatusRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EdGraphServicesStateReportingV1SetSubmissionStatusRequest`
        """
        model = EdGraphServicesStateReportingV1SetSubmissionStatusRequest()
        if include_optional:
            return EdGraphServicesStateReportingV1SetSubmissionStatusRequest(
                tenant_id = '',
                environment_id = '',
                reporting_period_id = '',
                submission_id = '',
                status = 'Unknown'
            )
        else:
            return EdGraphServicesStateReportingV1SetSubmissionStatusRequest(
        )
        """

    def testEdGraphServicesStateReportingV1SetSubmissionStatusRequest(self):
        """Test EdGraphServicesStateReportingV1SetSubmissionStatusRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
