# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.ed_graph_http_aggregators_tenant_api_services_state_reporting_v1_test_connection_by_type_request import EdGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionByTypeRequest

class TestEdGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionByTypeRequest(unittest.TestCase):
    """EdGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionByTypeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EdGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionByTypeRequest:
        """Test EdGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionByTypeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EdGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionByTypeRequest`
        """
        model = EdGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionByTypeRequest()
        if include_optional:
            return EdGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionByTypeRequest(
                id = '',
                type = '',
                tenant_id = '',
                environment_id = '',
                server = '',
                username = '',
                database = '',
                password = '',
                auth_url = '',
                resources_url = '',
                api_key = '',
                api_secret = ''
            )
        else:
            return EdGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionByTypeRequest(
        )
        """

    def testEdGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionByTypeRequest(self):
        """Test EdGraphHttpAggregatorsTenantApiServicesStateReportingV1TestConnectionByTypeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
