# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.ed_graph_http_aggregators_tenant_api_services_connectors_extensions_adls_gen2_connector_profile_dto import EdGraphHttpAggregatorsTenantApiServicesConnectorsExtensionsADLSGen2ConnectorProfileDTO

class TestEdGraphHttpAggregatorsTenantApiServicesConnectorsExtensionsADLSGen2ConnectorProfileDTO(unittest.TestCase):
    """EdGraphHttpAggregatorsTenantApiServicesConnectorsExtensionsADLSGen2ConnectorProfileDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EdGraphHttpAggregatorsTenantApiServicesConnectorsExtensionsADLSGen2ConnectorProfileDTO:
        """Test EdGraphHttpAggregatorsTenantApiServicesConnectorsExtensionsADLSGen2ConnectorProfileDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EdGraphHttpAggregatorsTenantApiServicesConnectorsExtensionsADLSGen2ConnectorProfileDTO`
        """
        model = EdGraphHttpAggregatorsTenantApiServicesConnectorsExtensionsADLSGen2ConnectorProfileDTO()
        if include_optional:
            return EdGraphHttpAggregatorsTenantApiServicesConnectorsExtensionsADLSGen2ConnectorProfileDTO(
                id = '',
                tenant_id = '',
                connector_type = '',
                connector_name = '',
                workspace_name = '',
                authentication_type = edgraph_platform_client.models.analytics_api/adls_gen2_connectors/v1/authentication_type.AnalyticsApi.ADLSGen2Connectors.V1.AuthenticationType(
                    service_principal_authentication = edgraph_platform_client.models.analytics_api/adls_gen2_connectors/v1/service_principal_authentication.AnalyticsApi.ADLSGen2Connectors.V1.ServicePrincipalAuthentication(
                        azure_tenant_id = '', 
                        client = '', 
                        secret = '', ), ),
                pipeline = edgraph_platform_client.models.ed_graph/http_aggregators/tenant/api/services/connectors/extensions/adls_gen2_connector_profile_pipeline_dto.EdGraph.HttpAggregators.Tenant.Api.Services.Connectors.Extensions.ADLSGen2ConnectorProfilePipelineDTO(
                    name = '', 
                    parameters = null, ),
                metadata = None,
                created_by = '',
                created_date_time = '',
                last_modified_by = '',
                last_modified_date_time = '',
                is_deleted = True,
                deleted_by = '',
                deleted_date_time = ''
            )
        else:
            return EdGraphHttpAggregatorsTenantApiServicesConnectorsExtensionsADLSGen2ConnectorProfileDTO(
        )
        """

    def testEdGraphHttpAggregatorsTenantApiServicesConnectorsExtensionsADLSGen2ConnectorProfileDTO(self):
        """Test EdGraphHttpAggregatorsTenantApiServicesConnectorsExtensionsADLSGen2ConnectorProfileDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
