# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.analytics_api_groups_v1_analytics_group_user import AnalyticsApiGroupsV1AnalyticsGroupUser

class TestAnalyticsApiGroupsV1AnalyticsGroupUser(unittest.TestCase):
    """AnalyticsApiGroupsV1AnalyticsGroupUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnalyticsApiGroupsV1AnalyticsGroupUser:
        """Test AnalyticsApiGroupsV1AnalyticsGroupUser
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnalyticsApiGroupsV1AnalyticsGroupUser`
        """
        model = AnalyticsApiGroupsV1AnalyticsGroupUser()
        if include_optional:
            return AnalyticsApiGroupsV1AnalyticsGroupUser(
                display_name = '',
                email_address = '',
                group_user_access_right = '',
                identifier = '',
                principal_type = ''
            )
        else:
            return AnalyticsApiGroupsV1AnalyticsGroupUser(
        )
        """

    def testAnalyticsApiGroupsV1AnalyticsGroupUser(self):
        """Test AnalyticsApiGroupsV1AnalyticsGroupUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
