# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.api.instances_vendors_api import InstancesVendorsApi


class TestInstancesVendorsApi(unittest.TestCase):
    """InstancesVendorsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InstancesVendorsApi()

    def tearDown(self) -> None:
        pass

    def test_create_vendor_async(self) -> None:
        """Test case for create_vendor_async

        Creates a new Vendor.
        """
        pass

    def test_delete_vendor_async(self) -> None:
        """Test case for delete_vendor_async

        Deletes a Vendor.
        """
        pass

    def test_get_vendor_by_id_async(self) -> None:
        """Test case for get_vendor_by_id_async

        Retrieves a Vendor by ID.
        """
        pass

    def test_get_vendors_async(self) -> None:
        """Test case for get_vendors_async

        Retrieves a list of Vendors.
        """
        pass

    def test_sync_vendor_async(self) -> None:
        """Test case for sync_vendor_async

        Copies a Vendor from one instance to another/other instance(s).
        """
        pass

    def test_update_vendor_async(self) -> None:
        """Test case for update_vendor_async

        Updates a Vendor.
        """
        pass


if __name__ == '__main__':
    unittest.main()
