# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.ed_graph_http_aggregators_tenant_api_services_observations_get_academic_subjects_count_response import EdGraphHttpAggregatorsTenantApiServicesObservationsGetAcademicSubjectsCountResponse

class TestEdGraphHttpAggregatorsTenantApiServicesObservationsGetAcademicSubjectsCountResponse(unittest.TestCase):
    """EdGraphHttpAggregatorsTenantApiServicesObservationsGetAcademicSubjectsCountResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EdGraphHttpAggregatorsTenantApiServicesObservationsGetAcademicSubjectsCountResponse:
        """Test EdGraphHttpAggregatorsTenantApiServicesObservationsGetAcademicSubjectsCountResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EdGraphHttpAggregatorsTenantApiServicesObservationsGetAcademicSubjectsCountResponse`
        """
        model = EdGraphHttpAggregatorsTenantApiServicesObservationsGetAcademicSubjectsCountResponse()
        if include_optional:
            return EdGraphHttpAggregatorsTenantApiServicesObservationsGetAcademicSubjectsCountResponse(
                tenant_id = '',
                total_count = 56
            )
        else:
            return EdGraphHttpAggregatorsTenantApiServicesObservationsGetAcademicSubjectsCountResponse(
        )
        """

    def testEdGraphHttpAggregatorsTenantApiServicesObservationsGetAcademicSubjectsCountResponse(self):
        """Test EdGraphHttpAggregatorsTenantApiServicesObservationsGetAcademicSubjectsCountResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
