# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.data_sync_api_job_v1_job_status import DataSyncApiJobV1JobStatus

class TestDataSyncApiJobV1JobStatus(unittest.TestCase):
    """DataSyncApiJobV1JobStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataSyncApiJobV1JobStatus(self):
        """Test DataSyncApiJobV1JobStatus"""
        # inst = DataSyncApiJobV1JobStatus()

if __name__ == '__main__':
    unittest.main()
