# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.ed_graph_http_aggregators_tenant_api_services_observations_observation_profile_response_paginated_items_view_model import EdGraphHttpAggregatorsTenantApiServicesObservationsObservationProfileResponsePaginatedItemsViewModel

class TestEdGraphHttpAggregatorsTenantApiServicesObservationsObservationProfileResponsePaginatedItemsViewModel(unittest.TestCase):
    """EdGraphHttpAggregatorsTenantApiServicesObservationsObservationProfileResponsePaginatedItemsViewModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EdGraphHttpAggregatorsTenantApiServicesObservationsObservationProfileResponsePaginatedItemsViewModel:
        """Test EdGraphHttpAggregatorsTenantApiServicesObservationsObservationProfileResponsePaginatedItemsViewModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EdGraphHttpAggregatorsTenantApiServicesObservationsObservationProfileResponsePaginatedItemsViewModel`
        """
        model = EdGraphHttpAggregatorsTenantApiServicesObservationsObservationProfileResponsePaginatedItemsViewModel()
        if include_optional:
            return EdGraphHttpAggregatorsTenantApiServicesObservationsObservationProfileResponsePaginatedItemsViewModel(
                page_index = 56,
                page_size = 56,
                count = 56,
                data = [
                    edgraph_platform_client.models.ed_graph/http_aggregators/tenant/api/services/observations/observation_profile_response.EdGraph.HttpAggregators.Tenant.Api.Services.Observations.ObservationProfileResponse(
                        id = '', 
                        tenant_id = '', 
                        campus = '', 
                        observer_id = '', 
                        observer_name = '', 
                        evaluee_id = '', 
                        evaluee_name = '', 
                        form_id = '', 
                        form_version = '', 
                        status = '', 
                        created_by = '', 
                        is_deleted = True, 
                        class = '', 
                        observation_date = '', 
                        submission_date = '', 
                        created_date_time = '', 
                        last_modified_by = '', 
                        last_modified_date_time = '', 
                        deleted_by = '', 
                        deleted_date_time = '', )
                    ]
            )
        else:
            return EdGraphHttpAggregatorsTenantApiServicesObservationsObservationProfileResponsePaginatedItemsViewModel(
        )
        """

    def testEdGraphHttpAggregatorsTenantApiServicesObservationsObservationProfileResponsePaginatedItemsViewModel(self):
        """Test EdGraphHttpAggregatorsTenantApiServicesObservationsObservationProfileResponsePaginatedItemsViewModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
