# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.identity_api_invitation_v1_assign_license_request import IdentityApiInvitationV1AssignLicenseRequest

class TestIdentityApiInvitationV1AssignLicenseRequest(unittest.TestCase):
    """IdentityApiInvitationV1AssignLicenseRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IdentityApiInvitationV1AssignLicenseRequest:
        """Test IdentityApiInvitationV1AssignLicenseRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IdentityApiInvitationV1AssignLicenseRequest`
        """
        model = IdentityApiInvitationV1AssignLicenseRequest()
        if include_optional:
            return IdentityApiInvitationV1AssignLicenseRequest(
                tenant_id = '',
                subscription_id = '',
                application_id = '',
                user_id = '',
                roles = [
                    ''
                    ]
            )
        else:
            return IdentityApiInvitationV1AssignLicenseRequest(
        )
        """

    def testIdentityApiInvitationV1AssignLicenseRequest(self):
        """Test IdentityApiInvitationV1AssignLicenseRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
