# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.form_api_questions_v1_question_visibility_condition import FormApiQuestionsV1QuestionVisibilityCondition

class TestFormApiQuestionsV1QuestionVisibilityCondition(unittest.TestCase):
    """FormApiQuestionsV1QuestionVisibilityCondition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FormApiQuestionsV1QuestionVisibilityCondition:
        """Test FormApiQuestionsV1QuestionVisibilityCondition
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FormApiQuestionsV1QuestionVisibilityCondition`
        """
        model = FormApiQuestionsV1QuestionVisibilityCondition()
        if include_optional:
            return FormApiQuestionsV1QuestionVisibilityCondition(
                logic = '',
                rules = [
                    edgraph_platform_client.models.form_api/questions/v1/question_visibility_rule.FormApi.Questions.V1.QuestionVisibilityRule(
                        field_id = '', 
                        operator = '', 
                        value = '', )
                    ]
            )
        else:
            return FormApiQuestionsV1QuestionVisibilityCondition(
        )
        """

    def testFormApiQuestionsV1QuestionVisibilityCondition(self):
        """Test FormApiQuestionsV1QuestionVisibilityCondition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
