# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.validations_api_reporting_periods_v1_reporting_period_dto import ValidationsApiReportingPeriodsV1ReportingPeriodDto

class TestValidationsApiReportingPeriodsV1ReportingPeriodDto(unittest.TestCase):
    """ValidationsApiReportingPeriodsV1ReportingPeriodDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidationsApiReportingPeriodsV1ReportingPeriodDto:
        """Test ValidationsApiReportingPeriodsV1ReportingPeriodDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidationsApiReportingPeriodsV1ReportingPeriodDto`
        """
        model = ValidationsApiReportingPeriodsV1ReportingPeriodDto()
        if include_optional:
            return ValidationsApiReportingPeriodsV1ReportingPeriodDto(
                id = '',
                created_at = '',
                created_by = '',
                updated_at = '',
                updated_by = '',
                deleted_at = '',
                deleted_by = '',
                tenant_id = '',
                tag_id = '',
                rule_ids = [
                    ''
                    ],
                code = '',
                display_name = '',
                start_date = '',
                end_date = '',
                close_date = '',
                re_submission_date = '',
                auto_run_nightly = True,
                selected = True,
                last_run = edgraph_platform_client.models.validations_api/reporting_periods/v1/reporting_period_validations_run_dto.ValidationsApi.ReportingPeriods.V1.ReportingPeriodValidationsRunDto(
                    requested_at = '', 
                    job_execution_id = '', 
                    job_id = '', 
                    status = '', 
                    queued_date_time = '', 
                    start_date_time = '', 
                    end_date_time = '', ),
                latest_submission_request_date = '',
                latest_submission_id = ''
            )
        else:
            return ValidationsApiReportingPeriodsV1ReportingPeriodDto(
        )
        """

    def testValidationsApiReportingPeriodsV1ReportingPeriodDto(self):
        """Test ValidationsApiReportingPeriodsV1ReportingPeriodDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
