# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.tenant_api_tenant_v1_tenant_branding_response import TenantApiTenantV1TenantBrandingResponse

class TestTenantApiTenantV1TenantBrandingResponse(unittest.TestCase):
    """TenantApiTenantV1TenantBrandingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantApiTenantV1TenantBrandingResponse:
        """Test TenantApiTenantV1TenantBrandingResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantApiTenantV1TenantBrandingResponse`
        """
        model = TenantApiTenantV1TenantBrandingResponse()
        if include_optional:
            return TenantApiTenantV1TenantBrandingResponse(
                enabled = True,
                brand_name = '',
                logo = edgraph_platform_client.models.tenant_api/tenant/v1/tenant_branding_logo.TenantApi.Tenant.V1.TenantBrandingLogo(
                    url = '', 
                    blob_name = '', 
                    container_name = '', ),
                background = edgraph_platform_client.models.tenant_api/tenant/v1/tenant_branding_background.TenantApi.Tenant.V1.TenantBrandingBackground(
                    url = '', 
                    blob_name = '', 
                    container_name = '', )
            )
        else:
            return TenantApiTenantV1TenantBrandingResponse(
        )
        """

    def testTenantApiTenantV1TenantBrandingResponse(self):
        """Test TenantApiTenantV1TenantBrandingResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
