# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.ims_admin_api_v1_instances_get_instance_csv_export_response import IMSAdminApiV1InstancesGetInstanceCsvExportResponse

class TestIMSAdminApiV1InstancesGetInstanceCsvExportResponse(unittest.TestCase):
    """IMSAdminApiV1InstancesGetInstanceCsvExportResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IMSAdminApiV1InstancesGetInstanceCsvExportResponse:
        """Test IMSAdminApiV1InstancesGetInstanceCsvExportResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IMSAdminApiV1InstancesGetInstanceCsvExportResponse`
        """
        model = IMSAdminApiV1InstancesGetInstanceCsvExportResponse()
        if include_optional:
            return IMSAdminApiV1InstancesGetInstanceCsvExportResponse(
                download_uri = ''
            )
        else:
            return IMSAdminApiV1InstancesGetInstanceCsvExportResponse(
        )
        """

    def testIMSAdminApiV1InstancesGetInstanceCsvExportResponse(self):
        """Test IMSAdminApiV1InstancesGetInstanceCsvExportResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
