# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.ed_graph_http_aggregators_tenant_api_controllers_v2_create_client_setting_request_body import EdGraphHttpAggregatorsTenantApiControllersV2CreateClientSettingRequestBody

class TestEdGraphHttpAggregatorsTenantApiControllersV2CreateClientSettingRequestBody(unittest.TestCase):
    """EdGraphHttpAggregatorsTenantApiControllersV2CreateClientSettingRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EdGraphHttpAggregatorsTenantApiControllersV2CreateClientSettingRequestBody:
        """Test EdGraphHttpAggregatorsTenantApiControllersV2CreateClientSettingRequestBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EdGraphHttpAggregatorsTenantApiControllersV2CreateClientSettingRequestBody`
        """
        model = EdGraphHttpAggregatorsTenantApiControllersV2CreateClientSettingRequestBody()
        if include_optional:
            return EdGraphHttpAggregatorsTenantApiControllersV2CreateClientSettingRequestBody(
                setting_id = '',
                setting_type_id = '',
                provider = '',
                code = '',
                application_id = '',
                value = None
            )
        else:
            return EdGraphHttpAggregatorsTenantApiControllersV2CreateClientSettingRequestBody(
        )
        """

    def testEdGraphHttpAggregatorsTenantApiControllersV2CreateClientSettingRequestBody(self):
        """Test EdGraphHttpAggregatorsTenantApiControllersV2CreateClientSettingRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
