# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.identity_api_instructional_insights_v1_instructional_insights_security_sync_job_execution_message import IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobExecutionMessage

class TestIdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobExecutionMessage(unittest.TestCase):
    """IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobExecutionMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobExecutionMessage:
        """Test IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobExecutionMessage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobExecutionMessage`
        """
        model = IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobExecutionMessage()
        if include_optional:
            return IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobExecutionMessage(
                execution_id = '',
                tenant_id = '',
                job_id = '',
                status = '',
                queued_date_time = '',
                start_date_time = '',
                cancel_date_time = '',
                end_date_time = '',
                input = '',
                output = '',
                metrics = [
                    edgraph_platform_client.models.identity_api/instructional_insights/v1/instructional_insights_security_sync_job_execution_metric_message.IdentityApi.InstructionalInsights.V1.InstructionalInsightsSecuritySyncJobExecutionMetricMessage(
                        entity = '', 
                        processed = 56, 
                        success = 56, 
                        errors = 56, )
                    ]
            )
        else:
            return IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobExecutionMessage(
        )
        """

    def testIdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobExecutionMessage(self):
        """Test IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobExecutionMessage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
