# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.tenant_api_tenant_v1_update_domain_request import TenantApiTenantV1UpdateDomainRequest

class TestTenantApiTenantV1UpdateDomainRequest(unittest.TestCase):
    """TenantApiTenantV1UpdateDomainRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantApiTenantV1UpdateDomainRequest:
        """Test TenantApiTenantV1UpdateDomainRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantApiTenantV1UpdateDomainRequest`
        """
        model = TenantApiTenantV1UpdateDomainRequest()
        if include_optional:
            return TenantApiTenantV1UpdateDomainRequest(
                tenant_id = '',
                old_domain_name = '',
                new_domain_name = '',
                domain_status = 'Unknown',
                auto_assign_users = True,
                manually_verified = True
            )
        else:
            return TenantApiTenantV1UpdateDomainRequest(
        )
        """

    def testTenantApiTenantV1UpdateDomainRequest(self):
        """Test TenantApiTenantV1UpdateDomainRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
