# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import StrictInt, StrictStr
from typing import Optional
from edgraph_platform_client.models.identity_api_instructional_insights_v1_create_instructional_insights_security_sync_job_request import IdentityApiInstructionalInsightsV1CreateInstructionalInsightsSecuritySyncJobRequest
from edgraph_platform_client.models.identity_api_instructional_insights_v1_instructional_insights_security_sync_job_created_response import IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobCreatedResponse
from edgraph_platform_client.models.identity_api_instructional_insights_v1_instructional_insights_security_sync_job_executed_response import IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobExecutedResponse
from edgraph_platform_client.models.identity_api_instructional_insights_v1_instructional_insights_security_sync_job_response import IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobResponse
from edgraph_platform_client.models.identity_api_instructional_insights_v1_search_instructional_insights_security_sync_job_execution_logs_response import IdentityApiInstructionalInsightsV1SearchInstructionalInsightsSecuritySyncJobExecutionLogsResponse
from edgraph_platform_client.models.identity_api_instructional_insights_v1_search_instructional_insights_security_sync_job_executions_response import IdentityApiInstructionalInsightsV1SearchInstructionalInsightsSecuritySyncJobExecutionsResponse
from edgraph_platform_client.models.identity_api_instructional_insights_v1_update_instructional_insights_security_sync_job_request import IdentityApiInstructionalInsightsV1UpdateInstructionalInsightsSecuritySyncJobRequest
from edgraph_platform_client.models.microsoft_asp_net_core_mvc_no_content_result import MicrosoftAspNetCoreMvcNoContentResult

from edgraph_platform_client.api_client import ApiClient, RequestSerialized
from edgraph_platform_client.api_response import ApiResponse
from edgraph_platform_client.rest import RESTResponseType


class TenantJobsInstructionalInsightsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def create_instructional_insights_security_sync_job(
        self,
        tenant_id: StrictStr,
        identity_api_instructional_insights_v1_create_instructional_insights_security_sync_job_request: Optional[IdentityApiInstructionalInsightsV1CreateInstructionalInsightsSecuritySyncJobRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobCreatedResponse:
        """Creates an Instructional Insights Security Sync Job for a given tenant


        :param tenant_id:  (required)
        :type tenant_id: str
        :param identity_api_instructional_insights_v1_create_instructional_insights_security_sync_job_request: 
        :type identity_api_instructional_insights_v1_create_instructional_insights_security_sync_job_request: IdentityApiInstructionalInsightsV1CreateInstructionalInsightsSecuritySyncJobRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_instructional_insights_security_sync_job_serialize(
            tenant_id=tenant_id,
            identity_api_instructional_insights_v1_create_instructional_insights_security_sync_job_request=identity_api_instructional_insights_v1_create_instructional_insights_security_sync_job_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '401': "EdGraphCommonErrorsCoreProblemDetails",
            '403': "EdGraphCommonErrorsCoreProblemDetails",
            '500': "EdGraphCommonErrorsCoreProblemDetails",
            '200': "IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobCreatedResponse",
            '400': "MicrosoftAspNetCoreMvcValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def create_instructional_insights_security_sync_job_with_http_info(
        self,
        tenant_id: StrictStr,
        identity_api_instructional_insights_v1_create_instructional_insights_security_sync_job_request: Optional[IdentityApiInstructionalInsightsV1CreateInstructionalInsightsSecuritySyncJobRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobCreatedResponse]:
        """Creates an Instructional Insights Security Sync Job for a given tenant


        :param tenant_id:  (required)
        :type tenant_id: str
        :param identity_api_instructional_insights_v1_create_instructional_insights_security_sync_job_request: 
        :type identity_api_instructional_insights_v1_create_instructional_insights_security_sync_job_request: IdentityApiInstructionalInsightsV1CreateInstructionalInsightsSecuritySyncJobRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_instructional_insights_security_sync_job_serialize(
            tenant_id=tenant_id,
            identity_api_instructional_insights_v1_create_instructional_insights_security_sync_job_request=identity_api_instructional_insights_v1_create_instructional_insights_security_sync_job_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '401': "EdGraphCommonErrorsCoreProblemDetails",
            '403': "EdGraphCommonErrorsCoreProblemDetails",
            '500': "EdGraphCommonErrorsCoreProblemDetails",
            '200': "IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobCreatedResponse",
            '400': "MicrosoftAspNetCoreMvcValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def create_instructional_insights_security_sync_job_without_preload_content(
        self,
        tenant_id: StrictStr,
        identity_api_instructional_insights_v1_create_instructional_insights_security_sync_job_request: Optional[IdentityApiInstructionalInsightsV1CreateInstructionalInsightsSecuritySyncJobRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Creates an Instructional Insights Security Sync Job for a given tenant


        :param tenant_id:  (required)
        :type tenant_id: str
        :param identity_api_instructional_insights_v1_create_instructional_insights_security_sync_job_request: 
        :type identity_api_instructional_insights_v1_create_instructional_insights_security_sync_job_request: IdentityApiInstructionalInsightsV1CreateInstructionalInsightsSecuritySyncJobRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._create_instructional_insights_security_sync_job_serialize(
            tenant_id=tenant_id,
            identity_api_instructional_insights_v1_create_instructional_insights_security_sync_job_request=identity_api_instructional_insights_v1_create_instructional_insights_security_sync_job_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '401': "EdGraphCommonErrorsCoreProblemDetails",
            '403': "EdGraphCommonErrorsCoreProblemDetails",
            '500': "EdGraphCommonErrorsCoreProblemDetails",
            '200': "IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobCreatedResponse",
            '400': "MicrosoftAspNetCoreMvcValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _create_instructional_insights_security_sync_job_serialize(
        self,
        tenant_id,
        identity_api_instructional_insights_v1_create_instructional_insights_security_sync_job_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if tenant_id is not None:
            _path_params['tenantId'] = tenant_id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if identity_api_instructional_insights_v1_create_instructional_insights_security_sync_job_request is not None:
            _body_params = identity_api_instructional_insights_v1_create_instructional_insights_security_sync_job_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json-patch+json', 
                        'application/json', 
                        'text/json', 
                        'application/*+json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'oauth2'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/tenants/{tenantId}/jobs/instructionalinsights',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def execute_instructional_insights_security_sync_job(
        self,
        tenant_id: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobExecutedResponse:
        """Executes an Instructional Insights Security Sync Job


        :param tenant_id:  (required)
        :type tenant_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._execute_instructional_insights_security_sync_job_serialize(
            tenant_id=tenant_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '401': "EdGraphCommonErrorsCoreProblemDetails",
            '403': "EdGraphCommonErrorsCoreProblemDetails",
            '500': "EdGraphCommonErrorsCoreProblemDetails",
            '202': "IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobExecutedResponse",
            '400': "MicrosoftAspNetCoreMvcValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def execute_instructional_insights_security_sync_job_with_http_info(
        self,
        tenant_id: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobExecutedResponse]:
        """Executes an Instructional Insights Security Sync Job


        :param tenant_id:  (required)
        :type tenant_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._execute_instructional_insights_security_sync_job_serialize(
            tenant_id=tenant_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '401': "EdGraphCommonErrorsCoreProblemDetails",
            '403': "EdGraphCommonErrorsCoreProblemDetails",
            '500': "EdGraphCommonErrorsCoreProblemDetails",
            '202': "IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobExecutedResponse",
            '400': "MicrosoftAspNetCoreMvcValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def execute_instructional_insights_security_sync_job_without_preload_content(
        self,
        tenant_id: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Executes an Instructional Insights Security Sync Job


        :param tenant_id:  (required)
        :type tenant_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._execute_instructional_insights_security_sync_job_serialize(
            tenant_id=tenant_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '401': "EdGraphCommonErrorsCoreProblemDetails",
            '403': "EdGraphCommonErrorsCoreProblemDetails",
            '500': "EdGraphCommonErrorsCoreProblemDetails",
            '202': "IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobExecutedResponse",
            '400': "MicrosoftAspNetCoreMvcValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _execute_instructional_insights_security_sync_job_serialize(
        self,
        tenant_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if tenant_id is not None:
            _path_params['tenantId'] = tenant_id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'oauth2'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/tenants/{tenantId}/jobs/instructionalinsights/execute',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_instructional_insights_security_sync_job(
        self,
        tenant_id: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobResponse:
        """Retrieves an Instructional Insights Security Sync Job for a given tenant


        :param tenant_id:  (required)
        :type tenant_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_instructional_insights_security_sync_job_serialize(
            tenant_id=tenant_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '401': "EdGraphCommonErrorsCoreProblemDetails",
            '403': "EdGraphCommonErrorsCoreProblemDetails",
            '500': "EdGraphCommonErrorsCoreProblemDetails",
            '200': "IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobResponse",
            '400': "MicrosoftAspNetCoreMvcValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_instructional_insights_security_sync_job_with_http_info(
        self,
        tenant_id: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobResponse]:
        """Retrieves an Instructional Insights Security Sync Job for a given tenant


        :param tenant_id:  (required)
        :type tenant_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_instructional_insights_security_sync_job_serialize(
            tenant_id=tenant_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '401': "EdGraphCommonErrorsCoreProblemDetails",
            '403': "EdGraphCommonErrorsCoreProblemDetails",
            '500': "EdGraphCommonErrorsCoreProblemDetails",
            '200': "IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobResponse",
            '400': "MicrosoftAspNetCoreMvcValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_instructional_insights_security_sync_job_without_preload_content(
        self,
        tenant_id: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Retrieves an Instructional Insights Security Sync Job for a given tenant


        :param tenant_id:  (required)
        :type tenant_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_instructional_insights_security_sync_job_serialize(
            tenant_id=tenant_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '401': "EdGraphCommonErrorsCoreProblemDetails",
            '403': "EdGraphCommonErrorsCoreProblemDetails",
            '500': "EdGraphCommonErrorsCoreProblemDetails",
            '200': "IdentityApiInstructionalInsightsV1InstructionalInsightsSecuritySyncJobResponse",
            '400': "MicrosoftAspNetCoreMvcValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_instructional_insights_security_sync_job_serialize(
        self,
        tenant_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if tenant_id is not None:
            _path_params['tenantId'] = tenant_id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'oauth2'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/tenants/{tenantId}/jobs/instructionalinsights',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def search_instructional_insights_security_sync_job_execution_logs(
        self,
        tenant_id: StrictStr,
        execution_id: StrictStr,
        job_id: Optional[StrictStr] = None,
        page_index: Optional[StrictInt] = None,
        page_size: Optional[StrictInt] = None,
        order_by: Optional[StrictStr] = None,
        level: Optional[StrictStr] = None,
        message: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> IdentityApiInstructionalInsightsV1SearchInstructionalInsightsSecuritySyncJobExecutionLogsResponse:
        """Searches Instructional Insights Security Sync Job Execution Logs for a given tenant and execution


        :param tenant_id:  (required)
        :type tenant_id: str
        :param execution_id:  (required)
        :type execution_id: str
        :param job_id: 
        :type job_id: str
        :param page_index: 
        :type page_index: int
        :param page_size: 
        :type page_size: int
        :param order_by: 
        :type order_by: str
        :param level: 
        :type level: str
        :param message: 
        :type message: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_instructional_insights_security_sync_job_execution_logs_serialize(
            tenant_id=tenant_id,
            execution_id=execution_id,
            job_id=job_id,
            page_index=page_index,
            page_size=page_size,
            order_by=order_by,
            level=level,
            message=message,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '401': "EdGraphCommonErrorsCoreProblemDetails",
            '403': "EdGraphCommonErrorsCoreProblemDetails",
            '500': "EdGraphCommonErrorsCoreProblemDetails",
            '200': "IdentityApiInstructionalInsightsV1SearchInstructionalInsightsSecuritySyncJobExecutionLogsResponse",
            '400': "MicrosoftAspNetCoreMvcValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def search_instructional_insights_security_sync_job_execution_logs_with_http_info(
        self,
        tenant_id: StrictStr,
        execution_id: StrictStr,
        job_id: Optional[StrictStr] = None,
        page_index: Optional[StrictInt] = None,
        page_size: Optional[StrictInt] = None,
        order_by: Optional[StrictStr] = None,
        level: Optional[StrictStr] = None,
        message: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[IdentityApiInstructionalInsightsV1SearchInstructionalInsightsSecuritySyncJobExecutionLogsResponse]:
        """Searches Instructional Insights Security Sync Job Execution Logs for a given tenant and execution


        :param tenant_id:  (required)
        :type tenant_id: str
        :param execution_id:  (required)
        :type execution_id: str
        :param job_id: 
        :type job_id: str
        :param page_index: 
        :type page_index: int
        :param page_size: 
        :type page_size: int
        :param order_by: 
        :type order_by: str
        :param level: 
        :type level: str
        :param message: 
        :type message: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_instructional_insights_security_sync_job_execution_logs_serialize(
            tenant_id=tenant_id,
            execution_id=execution_id,
            job_id=job_id,
            page_index=page_index,
            page_size=page_size,
            order_by=order_by,
            level=level,
            message=message,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '401': "EdGraphCommonErrorsCoreProblemDetails",
            '403': "EdGraphCommonErrorsCoreProblemDetails",
            '500': "EdGraphCommonErrorsCoreProblemDetails",
            '200': "IdentityApiInstructionalInsightsV1SearchInstructionalInsightsSecuritySyncJobExecutionLogsResponse",
            '400': "MicrosoftAspNetCoreMvcValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def search_instructional_insights_security_sync_job_execution_logs_without_preload_content(
        self,
        tenant_id: StrictStr,
        execution_id: StrictStr,
        job_id: Optional[StrictStr] = None,
        page_index: Optional[StrictInt] = None,
        page_size: Optional[StrictInt] = None,
        order_by: Optional[StrictStr] = None,
        level: Optional[StrictStr] = None,
        message: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Searches Instructional Insights Security Sync Job Execution Logs for a given tenant and execution


        :param tenant_id:  (required)
        :type tenant_id: str
        :param execution_id:  (required)
        :type execution_id: str
        :param job_id: 
        :type job_id: str
        :param page_index: 
        :type page_index: int
        :param page_size: 
        :type page_size: int
        :param order_by: 
        :type order_by: str
        :param level: 
        :type level: str
        :param message: 
        :type message: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_instructional_insights_security_sync_job_execution_logs_serialize(
            tenant_id=tenant_id,
            execution_id=execution_id,
            job_id=job_id,
            page_index=page_index,
            page_size=page_size,
            order_by=order_by,
            level=level,
            message=message,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '401': "EdGraphCommonErrorsCoreProblemDetails",
            '403': "EdGraphCommonErrorsCoreProblemDetails",
            '500': "EdGraphCommonErrorsCoreProblemDetails",
            '200': "IdentityApiInstructionalInsightsV1SearchInstructionalInsightsSecuritySyncJobExecutionLogsResponse",
            '400': "MicrosoftAspNetCoreMvcValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _search_instructional_insights_security_sync_job_execution_logs_serialize(
        self,
        tenant_id,
        execution_id,
        job_id,
        page_index,
        page_size,
        order_by,
        level,
        message,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if tenant_id is not None:
            _path_params['tenantId'] = tenant_id
        if execution_id is not None:
            _path_params['executionId'] = execution_id
        # process the query parameters
        if job_id is not None:
            
            _query_params.append(('jobId', job_id))
            
        if page_index is not None:
            
            _query_params.append(('pageIndex', page_index))
            
        if page_size is not None:
            
            _query_params.append(('pageSize', page_size))
            
        if order_by is not None:
            
            _query_params.append(('orderBy', order_by))
            
        if level is not None:
            
            _query_params.append(('level', level))
            
        if message is not None:
            
            _query_params.append(('message', message))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'oauth2'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/tenants/{tenantId}/jobs/instructionalinsights/executions/{executionId}/logs',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def search_instructional_insights_security_sync_job_executions(
        self,
        tenant_id: StrictStr,
        job_id: Optional[StrictStr] = None,
        page_index: Optional[StrictInt] = None,
        page_size: Optional[StrictInt] = None,
        order_by: Optional[StrictStr] = None,
        filter: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> IdentityApiInstructionalInsightsV1SearchInstructionalInsightsSecuritySyncJobExecutionsResponse:
        """Searches Instructional Insights Security Sync Job Executions for a given tenant


        :param tenant_id:  (required)
        :type tenant_id: str
        :param job_id: 
        :type job_id: str
        :param page_index: 
        :type page_index: int
        :param page_size: 
        :type page_size: int
        :param order_by: 
        :type order_by: str
        :param filter: 
        :type filter: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_instructional_insights_security_sync_job_executions_serialize(
            tenant_id=tenant_id,
            job_id=job_id,
            page_index=page_index,
            page_size=page_size,
            order_by=order_by,
            filter=filter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '401': "EdGraphCommonErrorsCoreProblemDetails",
            '403': "EdGraphCommonErrorsCoreProblemDetails",
            '500': "EdGraphCommonErrorsCoreProblemDetails",
            '200': "IdentityApiInstructionalInsightsV1SearchInstructionalInsightsSecuritySyncJobExecutionsResponse",
            '400': "MicrosoftAspNetCoreMvcValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def search_instructional_insights_security_sync_job_executions_with_http_info(
        self,
        tenant_id: StrictStr,
        job_id: Optional[StrictStr] = None,
        page_index: Optional[StrictInt] = None,
        page_size: Optional[StrictInt] = None,
        order_by: Optional[StrictStr] = None,
        filter: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[IdentityApiInstructionalInsightsV1SearchInstructionalInsightsSecuritySyncJobExecutionsResponse]:
        """Searches Instructional Insights Security Sync Job Executions for a given tenant


        :param tenant_id:  (required)
        :type tenant_id: str
        :param job_id: 
        :type job_id: str
        :param page_index: 
        :type page_index: int
        :param page_size: 
        :type page_size: int
        :param order_by: 
        :type order_by: str
        :param filter: 
        :type filter: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_instructional_insights_security_sync_job_executions_serialize(
            tenant_id=tenant_id,
            job_id=job_id,
            page_index=page_index,
            page_size=page_size,
            order_by=order_by,
            filter=filter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '401': "EdGraphCommonErrorsCoreProblemDetails",
            '403': "EdGraphCommonErrorsCoreProblemDetails",
            '500': "EdGraphCommonErrorsCoreProblemDetails",
            '200': "IdentityApiInstructionalInsightsV1SearchInstructionalInsightsSecuritySyncJobExecutionsResponse",
            '400': "MicrosoftAspNetCoreMvcValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def search_instructional_insights_security_sync_job_executions_without_preload_content(
        self,
        tenant_id: StrictStr,
        job_id: Optional[StrictStr] = None,
        page_index: Optional[StrictInt] = None,
        page_size: Optional[StrictInt] = None,
        order_by: Optional[StrictStr] = None,
        filter: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Searches Instructional Insights Security Sync Job Executions for a given tenant


        :param tenant_id:  (required)
        :type tenant_id: str
        :param job_id: 
        :type job_id: str
        :param page_index: 
        :type page_index: int
        :param page_size: 
        :type page_size: int
        :param order_by: 
        :type order_by: str
        :param filter: 
        :type filter: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_instructional_insights_security_sync_job_executions_serialize(
            tenant_id=tenant_id,
            job_id=job_id,
            page_index=page_index,
            page_size=page_size,
            order_by=order_by,
            filter=filter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '401': "EdGraphCommonErrorsCoreProblemDetails",
            '403': "EdGraphCommonErrorsCoreProblemDetails",
            '500': "EdGraphCommonErrorsCoreProblemDetails",
            '200': "IdentityApiInstructionalInsightsV1SearchInstructionalInsightsSecuritySyncJobExecutionsResponse",
            '400': "MicrosoftAspNetCoreMvcValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _search_instructional_insights_security_sync_job_executions_serialize(
        self,
        tenant_id,
        job_id,
        page_index,
        page_size,
        order_by,
        filter,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if tenant_id is not None:
            _path_params['tenantId'] = tenant_id
        # process the query parameters
        if job_id is not None:
            
            _query_params.append(('jobId', job_id))
            
        if page_index is not None:
            
            _query_params.append(('pageIndex', page_index))
            
        if page_size is not None:
            
            _query_params.append(('pageSize', page_size))
            
        if order_by is not None:
            
            _query_params.append(('orderBy', order_by))
            
        if filter is not None:
            
            _query_params.append(('filter', filter))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'oauth2'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/tenants/{tenantId}/jobs/instructionalinsights/executions',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def update_instructional_insights_security_sync_job(
        self,
        tenant_id: StrictStr,
        identity_api_instructional_insights_v1_update_instructional_insights_security_sync_job_request: Optional[IdentityApiInstructionalInsightsV1UpdateInstructionalInsightsSecuritySyncJobRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> MicrosoftAspNetCoreMvcNoContentResult:
        """Updates an Instructional Insights Security Sync Job for a given tenant


        :param tenant_id:  (required)
        :type tenant_id: str
        :param identity_api_instructional_insights_v1_update_instructional_insights_security_sync_job_request: 
        :type identity_api_instructional_insights_v1_update_instructional_insights_security_sync_job_request: IdentityApiInstructionalInsightsV1UpdateInstructionalInsightsSecuritySyncJobRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._update_instructional_insights_security_sync_job_serialize(
            tenant_id=tenant_id,
            identity_api_instructional_insights_v1_update_instructional_insights_security_sync_job_request=identity_api_instructional_insights_v1_update_instructional_insights_security_sync_job_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '401': "EdGraphCommonErrorsCoreProblemDetails",
            '403': "EdGraphCommonErrorsCoreProblemDetails",
            '500': "EdGraphCommonErrorsCoreProblemDetails",
            '204': "MicrosoftAspNetCoreMvcNoContentResult",
            '400': "MicrosoftAspNetCoreMvcValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def update_instructional_insights_security_sync_job_with_http_info(
        self,
        tenant_id: StrictStr,
        identity_api_instructional_insights_v1_update_instructional_insights_security_sync_job_request: Optional[IdentityApiInstructionalInsightsV1UpdateInstructionalInsightsSecuritySyncJobRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[MicrosoftAspNetCoreMvcNoContentResult]:
        """Updates an Instructional Insights Security Sync Job for a given tenant


        :param tenant_id:  (required)
        :type tenant_id: str
        :param identity_api_instructional_insights_v1_update_instructional_insights_security_sync_job_request: 
        :type identity_api_instructional_insights_v1_update_instructional_insights_security_sync_job_request: IdentityApiInstructionalInsightsV1UpdateInstructionalInsightsSecuritySyncJobRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._update_instructional_insights_security_sync_job_serialize(
            tenant_id=tenant_id,
            identity_api_instructional_insights_v1_update_instructional_insights_security_sync_job_request=identity_api_instructional_insights_v1_update_instructional_insights_security_sync_job_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '401': "EdGraphCommonErrorsCoreProblemDetails",
            '403': "EdGraphCommonErrorsCoreProblemDetails",
            '500': "EdGraphCommonErrorsCoreProblemDetails",
            '204': "MicrosoftAspNetCoreMvcNoContentResult",
            '400': "MicrosoftAspNetCoreMvcValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def update_instructional_insights_security_sync_job_without_preload_content(
        self,
        tenant_id: StrictStr,
        identity_api_instructional_insights_v1_update_instructional_insights_security_sync_job_request: Optional[IdentityApiInstructionalInsightsV1UpdateInstructionalInsightsSecuritySyncJobRequest] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Updates an Instructional Insights Security Sync Job for a given tenant


        :param tenant_id:  (required)
        :type tenant_id: str
        :param identity_api_instructional_insights_v1_update_instructional_insights_security_sync_job_request: 
        :type identity_api_instructional_insights_v1_update_instructional_insights_security_sync_job_request: IdentityApiInstructionalInsightsV1UpdateInstructionalInsightsSecuritySyncJobRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._update_instructional_insights_security_sync_job_serialize(
            tenant_id=tenant_id,
            identity_api_instructional_insights_v1_update_instructional_insights_security_sync_job_request=identity_api_instructional_insights_v1_update_instructional_insights_security_sync_job_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '401': "EdGraphCommonErrorsCoreProblemDetails",
            '403': "EdGraphCommonErrorsCoreProblemDetails",
            '500': "EdGraphCommonErrorsCoreProblemDetails",
            '204': "MicrosoftAspNetCoreMvcNoContentResult",
            '400': "MicrosoftAspNetCoreMvcValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _update_instructional_insights_security_sync_job_serialize(
        self,
        tenant_id,
        identity_api_instructional_insights_v1_update_instructional_insights_security_sync_job_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if tenant_id is not None:
            _path_params['tenantId'] = tenant_id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if identity_api_instructional_insights_v1_update_instructional_insights_security_sync_job_request is not None:
            _body_params = identity_api_instructional_insights_v1_update_instructional_insights_security_sync_job_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json-patch+json', 
                        'application/json', 
                        'text/json', 
                        'application/*+json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'oauth2'
        ]

        return self.api_client.param_serialize(
            method='PUT',
            resource_path='/tenants/{tenantId}/jobs/instructionalinsights',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


