# coding: utf-8

"""
    Tenant Api

    Tenant Api - v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.ed_graph_http_aggregators_tenant_api_controllers_v1_view_models_requests_send_invitation_request import EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsSendInvitationRequest

class TestEdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsSendInvitationRequest(unittest.TestCase):
    """EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsSendInvitationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsSendInvitationRequest:
        """Test EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsSendInvitationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsSendInvitationRequest`
        """
        model = EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsSendInvitationRequest()
        if include_optional:
            return EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsSendInvitationRequest(
                tenant_id = '',
                email = '',
                first_name = '',
                last_name = '',
                role = '',
                assign_license_requests = [
                    edgraph_platform_client.models.ed_graph/http_aggregators/tenant/api/controllers/v1/view_models/requests/licenses/assign_license_request.EdGraph.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Requests.Licenses.AssignLicenseRequest(
                        tenant_id = '', 
                        subscription_id = '', 
                        application_id = '', 
                        user_id = '', 
                        roles = [
                            ''
                            ], )
                    ],
                inviting_user_display_name = '',
                dont_send_email = True
            )
        else:
            return EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsSendInvitationRequest(
        )
        """

    def testEdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsSendInvitationRequest(self):
        """Test EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsSendInvitationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
