# coding: utf-8

"""
    Tenant Api

    Tenant Api - v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.api.users_education_organizations_api import UsersEducationOrganizationsApi


class TestUsersEducationOrganizationsApi(unittest.TestCase):
    """UsersEducationOrganizationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersEducationOrganizationsApi()

    def tearDown(self) -> None:
        pass

    def test_add_user_education_organization(self) -> None:
        """Test case for add_user_education_organization

        Adds an Education Organization to a user.
        """
        pass

    def test_get_user_education_organizations(self) -> None:
        """Test case for get_user_education_organizations

        Gets the Education Organizations of a user.
        """
        pass

    def test_remove_user_education_organization(self) -> None:
        """Test case for remove_user_education_organization

        Removes an Education Organization from a user.
        """
        pass

    def test_update_user_education_organization(self) -> None:
        """Test case for update_user_education_organization

        Updates the Education Organization of a user.
        """
        pass


if __name__ == '__main__':
    unittest.main()
