# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.tenant_api_tenant_v1_onboarding_steps_reponse import TenantApiTenantV1OnboardingStepsReponse

class TestTenantApiTenantV1OnboardingStepsReponse(unittest.TestCase):
    """TenantApiTenantV1OnboardingStepsReponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantApiTenantV1OnboardingStepsReponse:
        """Test TenantApiTenantV1OnboardingStepsReponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantApiTenantV1OnboardingStepsReponse`
        """
        model = TenantApiTenantV1OnboardingStepsReponse()
        if include_optional:
            return TenantApiTenantV1OnboardingStepsReponse(
                steps = [
                    edgraph_platform_client.models.tenant_api/tenant/v1/onboarding_step.TenantApi.Tenant.V1.OnboardingStep(
                        number = 56, 
                        description = '', 
                        status = '', 
                        started_at = '', 
                        completed_at = '', 
                        details = '', )
                    ]
            )
        else:
            return TenantApiTenantV1OnboardingStepsReponse(
        )
        """

    def testTenantApiTenantV1OnboardingStepsReponse(self):
        """Test TenantApiTenantV1OnboardingStepsReponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
