# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.validations_api_containers_v1_get_json_response import ValidationsApiContainersV1GetJsonResponse

class TestValidationsApiContainersV1GetJsonResponse(unittest.TestCase):
    """ValidationsApiContainersV1GetJsonResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidationsApiContainersV1GetJsonResponse:
        """Test ValidationsApiContainersV1GetJsonResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidationsApiContainersV1GetJsonResponse`
        """
        model = ValidationsApiContainersV1GetJsonResponse()
        if include_optional:
            return ValidationsApiContainersV1GetJsonResponse(
                collection_json = ''
            )
        else:
            return ValidationsApiContainersV1GetJsonResponse(
        )
        """

    def testValidationsApiContainersV1GetJsonResponse(self):
        """Test ValidationsApiContainersV1GetJsonResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
