# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.data_sync_api_ed_fi_roster_sync_v1_use_ssa_instead_of_seoaa_options import DataSyncApiEdFiRosterSyncV1UseSSAInsteadOfSEOAAOptions

class TestDataSyncApiEdFiRosterSyncV1UseSSAInsteadOfSEOAAOptions(unittest.TestCase):
    """DataSyncApiEdFiRosterSyncV1UseSSAInsteadOfSEOAAOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataSyncApiEdFiRosterSyncV1UseSSAInsteadOfSEOAAOptions:
        """Test DataSyncApiEdFiRosterSyncV1UseSSAInsteadOfSEOAAOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataSyncApiEdFiRosterSyncV1UseSSAInsteadOfSEOAAOptions`
        """
        model = DataSyncApiEdFiRosterSyncV1UseSSAInsteadOfSEOAAOptions()
        if include_optional:
            return DataSyncApiEdFiRosterSyncV1UseSSAInsteadOfSEOAAOptions(
                enabled = True,
                ignored_staff_classification_descriptors = [
                    ''
                    ],
                searched_classroom_position_descriptor = '',
                assigned_staff_classification_descriptor = ''
            )
        else:
            return DataSyncApiEdFiRosterSyncV1UseSSAInsteadOfSEOAAOptions(
        )
        """

    def testDataSyncApiEdFiRosterSyncV1UseSSAInsteadOfSEOAAOptions(self):
        """Test DataSyncApiEdFiRosterSyncV1UseSSAInsteadOfSEOAAOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
