# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.tenant_api_tenant_v1_organization import TenantApiTenantV1Organization

class TestTenantApiTenantV1Organization(unittest.TestCase):
    """TenantApiTenantV1Organization unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantApiTenantV1Organization:
        """Test TenantApiTenantV1Organization
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantApiTenantV1Organization`
        """
        model = TenantApiTenantV1Organization()
        if include_optional:
            return TenantApiTenantV1Organization(
                identifier_type = '',
                identifier_value = '',
                discriminator = '',
                source = '',
                short_name_of_institution = '',
                name_of_institution = '',
                include_in_jwt = True
            )
        else:
            return TenantApiTenantV1Organization(
        )
        """

    def testTenantApiTenantV1Organization(self):
        """Test TenantApiTenantV1Organization"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
