# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.edfi_admin_api_edfi_admin_v1_ed_fi_application_api_client_profile_response_paginated_items_view_model import EdfiAdminApiEdfiAdminV1EdFiApplicationApiClientProfileResponsePaginatedItemsViewModel

class TestEdfiAdminApiEdfiAdminV1EdFiApplicationApiClientProfileResponsePaginatedItemsViewModel(unittest.TestCase):
    """EdfiAdminApiEdfiAdminV1EdFiApplicationApiClientProfileResponsePaginatedItemsViewModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EdfiAdminApiEdfiAdminV1EdFiApplicationApiClientProfileResponsePaginatedItemsViewModel:
        """Test EdfiAdminApiEdfiAdminV1EdFiApplicationApiClientProfileResponsePaginatedItemsViewModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EdfiAdminApiEdfiAdminV1EdFiApplicationApiClientProfileResponsePaginatedItemsViewModel`
        """
        model = EdfiAdminApiEdfiAdminV1EdFiApplicationApiClientProfileResponsePaginatedItemsViewModel()
        if include_optional:
            return EdfiAdminApiEdfiAdminV1EdFiApplicationApiClientProfileResponsePaginatedItemsViewModel(
                page_index = 56,
                page_size = 56,
                count = 56,
                data = [
                    edgraph_platform_client.models.edfi_admin_api/edfi_admin/v1/ed_fi_application_api_client_profile_response.EdfiAdminApi.EdfiAdmin.V1.EdFiApplicationApiClientProfileResponse(
                        tenant_id = '', 
                        instance_id = '', 
                        api_client_id = 56, 
                        key = '', 
                        secret = '', 
                        name = '', 
                        is_approved = True, 
                        use_sandbox = True, 
                        sandbox_type = 56, 
                        application_id = 56, 
                        secret_is_hashed = True, 
                        key_status = '', )
                    ]
            )
        else:
            return EdfiAdminApiEdfiAdminV1EdFiApplicationApiClientProfileResponsePaginatedItemsViewModel(
        )
        """

    def testEdfiAdminApiEdfiAdminV1EdFiApplicationApiClientProfileResponsePaginatedItemsViewModel(self):
        """Test EdfiAdminApiEdfiAdminV1EdFiApplicationApiClientProfileResponsePaginatedItemsViewModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
