# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.ims_admin_api_v1_clients_access_token_type import IMSAdminApiV1ClientsAccessTokenType

class TestIMSAdminApiV1ClientsAccessTokenType(unittest.TestCase):
    """IMSAdminApiV1ClientsAccessTokenType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIMSAdminApiV1ClientsAccessTokenType(self):
        """Test IMSAdminApiV1ClientsAccessTokenType"""
        # inst = IMSAdminApiV1ClientsAccessTokenType()

if __name__ == '__main__':
    unittest.main()
