# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.application_api_application_v1_application_profile_response import ApplicationApiApplicationV1ApplicationProfileResponse

class TestApplicationApiApplicationV1ApplicationProfileResponse(unittest.TestCase):
    """ApplicationApiApplicationV1ApplicationProfileResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApplicationApiApplicationV1ApplicationProfileResponse:
        """Test ApplicationApiApplicationV1ApplicationProfileResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApplicationApiApplicationV1ApplicationProfileResponse`
        """
        model = ApplicationApiApplicationV1ApplicationProfileResponse()
        if include_optional:
            return ApplicationApiApplicationV1ApplicationProfileResponse(
                tenant_id = '',
                application_id = '',
                application_type = 'Unknown',
                application_name = '',
                application_uri = '',
                version = '',
                tooltip_text = '',
                application_description = '',
                tags = '',
                groups = '',
                application_status = 'Unknown',
                open_in_new_window = True,
                roles = [
                    edgraph_platform_client.models.application_api/application/v1/role.ApplicationApi.Application.V1.Role(
                        role_name = '', 
                        is_default = True, 
                        is_available_for_tenants = True, 
                        display_name = '', 
                        description = '', 
                        sort_order = 56, )
                    ],
                created_by = '',
                created_date_time = '',
                last_modified_by = '',
                last_modified_date_time = '',
                client_id = '',
                subscription_type = 'Auto'
            )
        else:
            return ApplicationApiApplicationV1ApplicationProfileResponse(
        )
        """

    def testApplicationApiApplicationV1ApplicationProfileResponse(self):
        """Test ApplicationApiApplicationV1ApplicationProfileResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
