# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.form_api_questions_v1_question_type import FormApiQuestionsV1QuestionType

class TestFormApiQuestionsV1QuestionType(unittest.TestCase):
    """FormApiQuestionsV1QuestionType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFormApiQuestionsV1QuestionType(self):
        """Test FormApiQuestionsV1QuestionType"""
        # inst = FormApiQuestionsV1QuestionType()

if __name__ == '__main__':
    unittest.main()
