# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.validations_api_jobs_v1_data_refresh_type import ValidationsApiJobsV1DataRefreshType

class TestValidationsApiJobsV1DataRefreshType(unittest.TestCase):
    """ValidationsApiJobsV1DataRefreshType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testValidationsApiJobsV1DataRefreshType(self):
        """Test ValidationsApiJobsV1DataRefreshType"""
        # inst = ValidationsApiJobsV1DataRefreshType()

if __name__ == '__main__':
    unittest.main()
