# coding: utf-8

"""
    Tenant Api

    Tenant Api - v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.api.applications_api import ApplicationsApi


class TestApplicationsApi(unittest.TestCase):
    """ApplicationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApplicationsApi()

    def tearDown(self) -> None:
        pass

    def test_get_tenant_application_profile_by_id_async(self) -> None:
        """Test case for get_tenant_application_profile_by_id_async

        Retrieves an application
        """
        pass

    def test_get_tenant_applications_async(self) -> None:
        """Test case for get_tenant_applications_async

        Retrieves a list of applications associated to this tenant
        """
        pass


if __name__ == '__main__':
    unittest.main()
