# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.ims_admin_api_v1_instances_create_instance_request import IMSAdminApiV1InstancesCreateInstanceRequest

class TestIMSAdminApiV1InstancesCreateInstanceRequest(unittest.TestCase):
    """IMSAdminApiV1InstancesCreateInstanceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IMSAdminApiV1InstancesCreateInstanceRequest:
        """Test IMSAdminApiV1InstancesCreateInstanceRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IMSAdminApiV1InstancesCreateInstanceRequest`
        """
        model = IMSAdminApiV1InstancesCreateInstanceRequest()
        if include_optional:
            return IMSAdminApiV1InstancesCreateInstanceRequest(
                tenant_id = '',
                name = '',
                use_custom_id = True,
                custom_id = '',
                description = '',
                connection_id = '',
                tier = '',
                backup_code = '',
                school_year = 56
            )
        else:
            return IMSAdminApiV1InstancesCreateInstanceRequest(
        )
        """

    def testIMSAdminApiV1InstancesCreateInstanceRequest(self):
        """Test IMSAdminApiV1InstancesCreateInstanceRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
