# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.analytics_api_capacities_v1_resume_capacity_request import AnalyticsApiCapacitiesV1ResumeCapacityRequest

class TestAnalyticsApiCapacitiesV1ResumeCapacityRequest(unittest.TestCase):
    """AnalyticsApiCapacitiesV1ResumeCapacityRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnalyticsApiCapacitiesV1ResumeCapacityRequest:
        """Test AnalyticsApiCapacitiesV1ResumeCapacityRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnalyticsApiCapacitiesV1ResumeCapacityRequest`
        """
        model = AnalyticsApiCapacitiesV1ResumeCapacityRequest()
        if include_optional:
            return AnalyticsApiCapacitiesV1ResumeCapacityRequest(
                tenant_id = '',
                dedicated_capacity_name = ''
            )
        else:
            return AnalyticsApiCapacitiesV1ResumeCapacityRequest(
        )
        """

    def testAnalyticsApiCapacitiesV1ResumeCapacityRequest(self):
        """Test AnalyticsApiCapacitiesV1ResumeCapacityRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
