# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.form_api_forms_v1_form_updated_response import FormApiFormsV1FormUpdatedResponse

class TestFormApiFormsV1FormUpdatedResponse(unittest.TestCase):
    """FormApiFormsV1FormUpdatedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FormApiFormsV1FormUpdatedResponse:
        """Test FormApiFormsV1FormUpdatedResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FormApiFormsV1FormUpdatedResponse`
        """
        model = FormApiFormsV1FormUpdatedResponse()
        if include_optional:
            return FormApiFormsV1FormUpdatedResponse(
                id = '',
                tenant_id = ''
            )
        else:
            return FormApiFormsV1FormUpdatedResponse(
        )
        """

    def testFormApiFormsV1FormUpdatedResponse(self):
        """Test FormApiFormsV1FormUpdatedResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
