# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.api.onboarding_steps_api import OnboardingStepsApi


class TestOnboardingStepsApi(unittest.TestCase):
    """OnboardingStepsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OnboardingStepsApi()

    def tearDown(self) -> None:
        pass

    def test_create_onboarding_step(self) -> None:
        """Test case for create_onboarding_step

        Creates an Onboarding Step.
        """
        pass

    def test_get_onboarding_steps(self) -> None:
        """Test case for get_onboarding_steps

        Gets a list of Onboarding Steps.
        """
        pass

    def test_update_onboarding_step(self) -> None:
        """Test case for update_onboarding_step

        Updates the status of an Onboarding Step.
        """
        pass


if __name__ == '__main__':
    unittest.main()
