# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.form_api_forms_v1_create_full_question_request import FormApiFormsV1CreateFullQuestionRequest

class TestFormApiFormsV1CreateFullQuestionRequest(unittest.TestCase):
    """FormApiFormsV1CreateFullQuestionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FormApiFormsV1CreateFullQuestionRequest:
        """Test FormApiFormsV1CreateFullQuestionRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FormApiFormsV1CreateFullQuestionRequest`
        """
        model = FormApiFormsV1CreateFullQuestionRequest()
        if include_optional:
            return FormApiFormsV1CreateFullQuestionRequest(
                title = '',
                description = '',
                type = 'Unknown',
                required = True,
                default_value = '',
                validation = edgraph_platform_client.models.form_api/forms/v1/create_full_question_validation_request.FormApi.Forms.V1.CreateFullQuestionValidationRequest(
                    min_length = 56, 
                    max_length = 56, ),
                options = [
                    ''
                    ],
                order = 56,
                component = ''
            )
        else:
            return FormApiFormsV1CreateFullQuestionRequest(
        )
        """

    def testFormApiFormsV1CreateFullQuestionRequest(self):
        """Test FormApiFormsV1CreateFullQuestionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
