# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.api.environments_reporting_periods_categories_api import EnvironmentsReportingPeriodsCategoriesApi


class TestEnvironmentsReportingPeriodsCategoriesApi(unittest.TestCase):
    """EnvironmentsReportingPeriodsCategoriesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EnvironmentsReportingPeriodsCategoriesApi()

    def tearDown(self) -> None:
        pass

    def test_search_state_reporting_period_categories(self) -> None:
        """Test case for search_state_reporting_period_categories

        Retrieves the Categories of a Reporting Period.
        """
        pass

    def test_search_state_reporting_period_sub_categories(self) -> None:
        """Test case for search_state_reporting_period_sub_categories

        Retrieves the Sub-Categories of a Reporting Period.
        """
        pass


if __name__ == '__main__':
    unittest.main()
