# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.form_api_submissions_v1_submission_response_paginated_items_view_model import FormApiSubmissionsV1SubmissionResponsePaginatedItemsViewModel

class TestFormApiSubmissionsV1SubmissionResponsePaginatedItemsViewModel(unittest.TestCase):
    """FormApiSubmissionsV1SubmissionResponsePaginatedItemsViewModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FormApiSubmissionsV1SubmissionResponsePaginatedItemsViewModel:
        """Test FormApiSubmissionsV1SubmissionResponsePaginatedItemsViewModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FormApiSubmissionsV1SubmissionResponsePaginatedItemsViewModel`
        """
        model = FormApiSubmissionsV1SubmissionResponsePaginatedItemsViewModel()
        if include_optional:
            return FormApiSubmissionsV1SubmissionResponsePaginatedItemsViewModel(
                page_index = 56,
                page_size = 56,
                count = 56,
                data = [
                    edgraph_platform_client.models.form_api/submissions/v1/submission_response.FormApi.Submissions.V1.SubmissionResponse(
                        id = '', 
                        form_id = '', 
                        tenant_id = '', 
                        current_step = 56, 
                        data = '', 
                        created_by = '', 
                        created_date_time = '', 
                        last_modified_by = '', 
                        last_modified_date_time = '', 
                        deleted_by = '', 
                        deleted_date_time = '', 
                        is_deleted = True, 
                        name = '', 
                        email = '', )
                    ]
            )
        else:
            return FormApiSubmissionsV1SubmissionResponsePaginatedItemsViewModel(
        )
        """

    def testFormApiSubmissionsV1SubmissionResponsePaginatedItemsViewModel(self):
        """Test FormApiSubmissionsV1SubmissionResponsePaginatedItemsViewModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
