# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.edfi_admin_api_edfi_admin_v1_database_tier import EdfiAdminApiEdfiAdminV1DatabaseTier

class TestEdfiAdminApiEdfiAdminV1DatabaseTier(unittest.TestCase):
    """EdfiAdminApiEdfiAdminV1DatabaseTier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEdfiAdminApiEdfiAdminV1DatabaseTier(self):
        """Test EdfiAdminApiEdfiAdminV1DatabaseTier"""
        # inst = EdfiAdminApiEdfiAdminV1DatabaseTier()

if __name__ == '__main__':
    unittest.main()
