# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.ed_graph_platform_http_aggregators_tenant_api_controllers_v1_view_models_responses_user_cache_response import EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesUserCacheResponse

class TestEdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesUserCacheResponse(unittest.TestCase):
    """EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesUserCacheResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesUserCacheResponse:
        """Test EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesUserCacheResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesUserCacheResponse`
        """
        model = EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesUserCacheResponse()
        if include_optional:
            return EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesUserCacheResponse(
                user_name = '',
                email = '',
                first_name = '',
                last_name = '',
                preferences = [
                    edgraph_platform_client.models.identity_api/user/v1/preference.IdentityApi.User.V1.Preference(
                        tenant_id = '', 
                        client_id = '', 
                        code = '', 
                        value = '', )
                    ],
                tenants = [
                    edgraph_platform_client.models.ed_graph/platform/http_aggregators/tenant/api/controllers/v1/view_models/responses/user_cache_tenant_response.EdGraph.Platform.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Responses.UserCacheTenantResponse(
                        tenant_id = '', 
                        tenant_type = '', 
                        tenant_types = [
                            ''
                            ], 
                        organization_identifier = '', 
                        organization_name = '', 
                        state = '', 
                        tenant_status = '', 
                        is_demo = True, 
                        education_organizations = [
                            edgraph_platform_client.models.ed_graph/platform/http_aggregators/tenant/api/controllers/v1/view_models/responses/user_cache_tenant_education_organization_response.EdGraph.Platform.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Responses.UserCacheTenantEducationOrganizationResponse(
                                education_organization_id = 56, 
                                short_name_of_institution = '', 
                                name_of_institution = '', 
                                staff_classifications = [
                                    ''
                                    ], 
                                source = '', )
                            ], 
                        licenses = [
                            edgraph_platform_client.models.ed_graph/platform/http_aggregators/tenant/api/controllers/v1/view_models/responses/user_tenant_license.EdGraph.Platform.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Responses.UserTenantLicense(
                                application_id = '', 
                                application_name = '', 
                                start_date_time = '', 
                                end_date_time = '', 
                                roles = [
                                    edgraph_platform_client.models.ed_graph/platform/http_aggregators/tenant/api/controllers/v1/view_models/responses/user_tenant_license_role.EdGraph.Platform.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Responses.UserTenantLicenseRole(
                                        role = '', 
                                        is_implicitly_assigned = True, 
                                        status = '', 
                                        education_organization_id = 56, 
                                        staff_classification = '', 
                                        source = '', )
                                    ], )
                            ], )
                    ],
                browser_debug_enabled = True,
                extensions = [
                    edgraph_platform_client.models.identity_api/user/v1/user_extension.IdentityApi.User.V1.UserExtension(
                        code = '', 
                        data = '', )
                    ],
                selected_tenant = edgraph_platform_client.models.ed_graph/platform/http_aggregators/tenant/api/controllers/v1/view_models/responses/user_cache_tenant_response.EdGraph.Platform.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Responses.UserCacheTenantResponse(
                    tenant_id = '', 
                    tenant_type = '', 
                    tenant_types = [
                        ''
                        ], 
                    organization_identifier = '', 
                    organization_name = '', 
                    state = '', 
                    tenant_status = '', 
                    is_demo = True, 
                    education_organizations = [
                        edgraph_platform_client.models.ed_graph/platform/http_aggregators/tenant/api/controllers/v1/view_models/responses/user_cache_tenant_education_organization_response.EdGraph.Platform.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Responses.UserCacheTenantEducationOrganizationResponse(
                            education_organization_id = 56, 
                            short_name_of_institution = '', 
                            name_of_institution = '', 
                            staff_classifications = [
                                ''
                                ], 
                            source = '', )
                        ], 
                    licenses = [
                        edgraph_platform_client.models.ed_graph/platform/http_aggregators/tenant/api/controllers/v1/view_models/responses/user_tenant_license.EdGraph.Platform.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Responses.UserTenantLicense(
                            application_id = '', 
                            application_name = '', 
                            start_date_time = '', 
                            end_date_time = '', 
                            roles = [
                                edgraph_platform_client.models.ed_graph/platform/http_aggregators/tenant/api/controllers/v1/view_models/responses/user_tenant_license_role.EdGraph.Platform.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Responses.UserTenantLicenseRole(
                                    role = '', 
                                    is_implicitly_assigned = True, 
                                    status = '', 
                                    education_organization_id = 56, 
                                    staff_classification = '', 
                                    source = '', )
                                ], )
                        ], ),
                tenants_total_count = 56
            )
        else:
            return EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesUserCacheResponse(
        )
        """

    def testEdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesUserCacheResponse(self):
        """Test EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesUserCacheResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
