# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.validations_api_reporting_periods_v1_post_request import ValidationsApiReportingPeriodsV1PostRequest

class TestValidationsApiReportingPeriodsV1PostRequest(unittest.TestCase):
    """ValidationsApiReportingPeriodsV1PostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidationsApiReportingPeriodsV1PostRequest:
        """Test ValidationsApiReportingPeriodsV1PostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidationsApiReportingPeriodsV1PostRequest`
        """
        model = ValidationsApiReportingPeriodsV1PostRequest()
        if include_optional:
            return ValidationsApiReportingPeriodsV1PostRequest(
                tenant_id = '',
                reporting_period_id = '',
                category_ids = [
                    ''
                    ],
                school_year = 56
            )
        else:
            return ValidationsApiReportingPeriodsV1PostRequest(
        )
        """

    def testValidationsApiReportingPeriodsV1PostRequest(self):
        """Test ValidationsApiReportingPeriodsV1PostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
