# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.validations_api_jobs_v1_schedule import ValidationsApiJobsV1Schedule

class TestValidationsApiJobsV1Schedule(unittest.TestCase):
    """ValidationsApiJobsV1Schedule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidationsApiJobsV1Schedule:
        """Test ValidationsApiJobsV1Schedule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidationsApiJobsV1Schedule`
        """
        model = ValidationsApiJobsV1Schedule()
        if include_optional:
            return ValidationsApiJobsV1Schedule(
                enabled = True,
                begin_date = '',
                end_date = '',
                cron = '',
                time_zone = ''
            )
        else:
            return ValidationsApiJobsV1Schedule(
        )
        """

    def testValidationsApiJobsV1Schedule(self):
        """Test ValidationsApiJobsV1Schedule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
