# coding: utf-8

"""
    Tenant Api

    Tenant Api - v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.tenant_api_tenant_v1_subscription_profile_response import TenantApiTenantV1SubscriptionProfileResponse

class TestTenantApiTenantV1SubscriptionProfileResponse(unittest.TestCase):
    """TenantApiTenantV1SubscriptionProfileResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantApiTenantV1SubscriptionProfileResponse:
        """Test TenantApiTenantV1SubscriptionProfileResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantApiTenantV1SubscriptionProfileResponse`
        """
        model = TenantApiTenantV1SubscriptionProfileResponse()
        if include_optional:
            return TenantApiTenantV1SubscriptionProfileResponse(
                tenant_id = '',
                subscription_id = '',
                application_id = '',
                start_date_time = '',
                end_date_time = '',
                actual_end_date_time = '',
                grace_period = 56,
                number_of_licenses = 56,
                assigned_licenses = 56,
                max_assigned_licenses = 56,
                last_max_assigned_licenses_date_time = '',
                license_type = 'Unknown',
                subscription_status = 'Unknown',
                auto_assign = True,
                created_by = '',
                created_date_time = '',
                last_modified_by = '',
                last_modified_date_time = '',
                deleted_at = ''
            )
        else:
            return TenantApiTenantV1SubscriptionProfileResponse(
        )
        """

    def testTenantApiTenantV1SubscriptionProfileResponse(self):
        """Test TenantApiTenantV1SubscriptionProfileResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
