# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.edfi_admin_api_edfi_admin_v1_instance_resources_count_json_response import EdfiAdminApiEdfiAdminV1InstanceResourcesCountJsonResponse

class TestEdfiAdminApiEdfiAdminV1InstanceResourcesCountJsonResponse(unittest.TestCase):
    """EdfiAdminApiEdfiAdminV1InstanceResourcesCountJsonResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EdfiAdminApiEdfiAdminV1InstanceResourcesCountJsonResponse:
        """Test EdfiAdminApiEdfiAdminV1InstanceResourcesCountJsonResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EdfiAdminApiEdfiAdminV1InstanceResourcesCountJsonResponse`
        """
        model = EdfiAdminApiEdfiAdminV1InstanceResourcesCountJsonResponse()
        if include_optional:
            return EdfiAdminApiEdfiAdminV1InstanceResourcesCountJsonResponse(
                instance_resources_json = ''
            )
        else:
            return EdfiAdminApiEdfiAdminV1InstanceResourcesCountJsonResponse(
        )
        """

    def testEdfiAdminApiEdfiAdminV1InstanceResourcesCountJsonResponse(self):
        """Test EdfiAdminApiEdfiAdminV1InstanceResourcesCountJsonResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
