# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.identity_api_invitation_v1_invitation_status import IdentityApiInvitationV1InvitationStatus

class TestIdentityApiInvitationV1InvitationStatus(unittest.TestCase):
    """IdentityApiInvitationV1InvitationStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdentityApiInvitationV1InvitationStatus(self):
        """Test IdentityApiInvitationV1InvitationStatus"""
        # inst = IdentityApiInvitationV1InvitationStatus()

if __name__ == '__main__':
    unittest.main()
