# coding: utf-8

"""
    Tenant Api

    Tenant Api - v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.tenant_api_tenant_v1_create_domain_request import TenantApiTenantV1CreateDomainRequest

class TestTenantApiTenantV1CreateDomainRequest(unittest.TestCase):
    """TenantApiTenantV1CreateDomainRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantApiTenantV1CreateDomainRequest:
        """Test TenantApiTenantV1CreateDomainRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantApiTenantV1CreateDomainRequest`
        """
        model = TenantApiTenantV1CreateDomainRequest()
        if include_optional:
            return TenantApiTenantV1CreateDomainRequest(
                tenant_id = '',
                domain_name = '',
                domain_status = 'Unknown',
                auto_assign_users = True,
                manually_verified = True
            )
        else:
            return TenantApiTenantV1CreateDomainRequest(
        )
        """

    def testTenantApiTenantV1CreateDomainRequest(self):
        """Test TenantApiTenantV1CreateDomainRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
