# coding: utf-8

"""
    Tenant Api

    Tenant Api - v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.tenant_api_tenant_v1_domain_verified_response import TenantApiTenantV1DomainVerifiedResponse

class TestTenantApiTenantV1DomainVerifiedResponse(unittest.TestCase):
    """TenantApiTenantV1DomainVerifiedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantApiTenantV1DomainVerifiedResponse:
        """Test TenantApiTenantV1DomainVerifiedResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantApiTenantV1DomainVerifiedResponse`
        """
        model = TenantApiTenantV1DomainVerifiedResponse()
        if include_optional:
            return TenantApiTenantV1DomainVerifiedResponse(
                tenant_id = '',
                domain_name = '',
                domain_status = 'Unknown'
            )
        else:
            return TenantApiTenantV1DomainVerifiedResponse(
        )
        """

    def testTenantApiTenantV1DomainVerifiedResponse(self):
        """Test TenantApiTenantV1DomainVerifiedResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
