# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.analytics_api_configurations_v1_configuration_response import AnalyticsApiConfigurationsV1ConfigurationResponse

class TestAnalyticsApiConfigurationsV1ConfigurationResponse(unittest.TestCase):
    """AnalyticsApiConfigurationsV1ConfigurationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnalyticsApiConfigurationsV1ConfigurationResponse:
        """Test AnalyticsApiConfigurationsV1ConfigurationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnalyticsApiConfigurationsV1ConfigurationResponse`
        """
        model = AnalyticsApiConfigurationsV1ConfigurationResponse()
        if include_optional:
            return AnalyticsApiConfigurationsV1ConfigurationResponse(
                id = ''
            )
        else:
            return AnalyticsApiConfigurationsV1ConfigurationResponse(
        )
        """

    def testAnalyticsApiConfigurationsV1ConfigurationResponse(self):
        """Test AnalyticsApiConfigurationsV1ConfigurationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
