# coding: utf-8

"""
    Tenant Api

    Tenant Api - v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.application_api_application_v1_application_type import ApplicationApiApplicationV1ApplicationType

class TestApplicationApiApplicationV1ApplicationType(unittest.TestCase):
    """ApplicationApiApplicationV1ApplicationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicationApiApplicationV1ApplicationType(self):
        """Test ApplicationApiApplicationV1ApplicationType"""
        # inst = ApplicationApiApplicationV1ApplicationType()

if __name__ == '__main__':
    unittest.main()
