# coding: utf-8

"""
    Tenant Api

    Tenant Api - v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.api.organizations_api import OrganizationsApi


class TestOrganizationsApi(unittest.TestCase):
    """OrganizationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrganizationsApi()

    def tearDown(self) -> None:
        pass

    def test_create_organization_async(self) -> None:
        """Test case for create_organization_async

        Creates an Organization.
        """
        pass

    def test_delete_organization_async(self) -> None:
        """Test case for delete_organization_async

        Deletes an Organization.
        """
        pass

    def test_get_organization_by_id_async(self) -> None:
        """Test case for get_organization_by_id_async

        Retrieves an Organization by ID.
        """
        pass

    def test_get_organizations_async(self) -> None:
        """Test case for get_organizations_async

        Retrieves a list of Organizations.
        """
        pass

    def test_update_organization_async(self) -> None:
        """Test case for update_organization_async

        Updates an Organization.
        """
        pass


if __name__ == '__main__':
    unittest.main()
