# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from edgraph_platform_client.models.data_sync_api_job_execution_log_v1_message_type import DataSyncApiJobExecutionLogV1MessageType
from typing import Optional, Set
from typing_extensions import Self

class DataSyncApiJobExecutionLogV1JobExecutionLogEntry(BaseModel):
    """
    DataSyncApiJobExecutionLogV1JobExecutionLogEntry
    """ # noqa: E501
    tenant_id: Optional[StrictStr] = Field(default=None, alias="tenantId")
    job_id: Optional[StrictStr] = Field(default=None, alias="jobId")
    job_execution_id: Optional[StrictStr] = Field(default=None, alias="jobExecutionId")
    message: Optional[StrictStr] = None
    message_type: Optional[DataSyncApiJobExecutionLogV1MessageType] = Field(default=None, alias="messageType")
    logged_date_time: Optional[StrictStr] = Field(default=None, alias="loggedDateTime")
    error_code: Optional[StrictStr] = Field(default=None, alias="errorCode")
    __properties: ClassVar[List[str]] = ["tenantId", "jobId", "jobExecutionId", "message", "messageType", "loggedDateTime", "errorCode"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DataSyncApiJobExecutionLogV1JobExecutionLogEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if tenant_id (nullable) is None
        # and model_fields_set contains the field
        if self.tenant_id is None and "tenant_id" in self.model_fields_set:
            _dict['tenantId'] = None

        # set to None if job_id (nullable) is None
        # and model_fields_set contains the field
        if self.job_id is None and "job_id" in self.model_fields_set:
            _dict['jobId'] = None

        # set to None if job_execution_id (nullable) is None
        # and model_fields_set contains the field
        if self.job_execution_id is None and "job_execution_id" in self.model_fields_set:
            _dict['jobExecutionId'] = None

        # set to None if message (nullable) is None
        # and model_fields_set contains the field
        if self.message is None and "message" in self.model_fields_set:
            _dict['message'] = None

        # set to None if logged_date_time (nullable) is None
        # and model_fields_set contains the field
        if self.logged_date_time is None and "logged_date_time" in self.model_fields_set:
            _dict['loggedDateTime'] = None

        # set to None if error_code (nullable) is None
        # and model_fields_set contains the field
        if self.error_code is None and "error_code" in self.model_fields_set:
            _dict['errorCode'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DataSyncApiJobExecutionLogV1JobExecutionLogEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tenantId": obj.get("tenantId"),
            "jobId": obj.get("jobId"),
            "jobExecutionId": obj.get("jobExecutionId"),
            "message": obj.get("message"),
            "messageType": obj.get("messageType"),
            "loggedDateTime": obj.get("loggedDateTime"),
            "errorCode": obj.get("errorCode")
        })
        return _obj


