# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DataSyncApiProviderV1ConnectionMetadataField(BaseModel):
    """
    DataSyncApiProviderV1ConnectionMetadataField
    """ # noqa: E501
    tab: Optional[StrictStr] = None
    code: Optional[StrictStr] = None
    label: Optional[StrictStr] = None
    validation: Optional[StrictStr] = None
    order: Optional[StrictStr] = None
    display: Optional[StrictBool] = None
    default_value: Optional[StrictStr] = Field(default=None, alias="defaultValue")
    type: Optional[StrictStr] = None
    values: Optional[StrictStr] = None
    api: Optional[StrictStr] = None
    is_secret: Optional[StrictBool] = Field(default=None, alias="isSecret")
    __properties: ClassVar[List[str]] = ["tab", "code", "label", "validation", "order", "display", "defaultValue", "type", "values", "api", "isSecret"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DataSyncApiProviderV1ConnectionMetadataField from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if tab (nullable) is None
        # and model_fields_set contains the field
        if self.tab is None and "tab" in self.model_fields_set:
            _dict['tab'] = None

        # set to None if code (nullable) is None
        # and model_fields_set contains the field
        if self.code is None and "code" in self.model_fields_set:
            _dict['code'] = None

        # set to None if label (nullable) is None
        # and model_fields_set contains the field
        if self.label is None and "label" in self.model_fields_set:
            _dict['label'] = None

        # set to None if validation (nullable) is None
        # and model_fields_set contains the field
        if self.validation is None and "validation" in self.model_fields_set:
            _dict['validation'] = None

        # set to None if order (nullable) is None
        # and model_fields_set contains the field
        if self.order is None and "order" in self.model_fields_set:
            _dict['order'] = None

        # set to None if default_value (nullable) is None
        # and model_fields_set contains the field
        if self.default_value is None and "default_value" in self.model_fields_set:
            _dict['defaultValue'] = None

        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['type'] = None

        # set to None if values (nullable) is None
        # and model_fields_set contains the field
        if self.values is None and "values" in self.model_fields_set:
            _dict['values'] = None

        # set to None if api (nullable) is None
        # and model_fields_set contains the field
        if self.api is None and "api" in self.model_fields_set:
            _dict['api'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DataSyncApiProviderV1ConnectionMetadataField from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tab": obj.get("tab"),
            "code": obj.get("code"),
            "label": obj.get("label"),
            "validation": obj.get("validation"),
            "order": obj.get("order"),
            "display": obj.get("display"),
            "defaultValue": obj.get("defaultValue"),
            "type": obj.get("type"),
            "values": obj.get("values"),
            "api": obj.get("api"),
            "isSecret": obj.get("isSecret")
        })
        return _obj


