# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminContactOverrideHistoryEntryDto(BaseModel):
    """
    One entry in a contact's override history.
    """ # noqa: E501
    event_id: Optional[StrictStr] = Field(default=None, alias="eventId")
    detail: Optional[StrictStr] = Field(default=None, description="Which detail this entry is about: `email` or `phone`.")
    action: Optional[StrictStr] = Field(default=None, description="`set` or `removed`. A removal returns the detail to its SIS value.")
    previous_value: Optional[StrictStr] = Field(default=None, description="The value this entry superseded, if any. Superseded values are kept, never deleted.", alias="previousValue")
    new_value: Optional[StrictStr] = Field(default=None, alias="newValue")
    sis_value: Optional[StrictStr] = Field(default=None, alias="sisValue")
    overridden_by: Optional[StrictStr] = Field(default=None, alias="overriddenBy")
    overridden_at: Optional[datetime] = Field(default=None, alias="overriddenAt")
    acting_student_id: Optional[StrictStr] = Field(default=None, description="The student whose screen the change was made from, when one was recorded.", alias="actingStudentId")
    student_ids: Optional[List[StrictStr]] = Field(default=None, alias="studentIds")
    __properties: ClassVar[List[str]] = ["eventId", "detail", "action", "previousValue", "newValue", "sisValue", "overriddenBy", "overriddenAt", "actingStudentId", "studentIds"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminContactOverrideHistoryEntryDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if event_id (nullable) is None
        # and model_fields_set contains the field
        if self.event_id is None and "event_id" in self.model_fields_set:
            _dict['eventId'] = None

        # set to None if detail (nullable) is None
        # and model_fields_set contains the field
        if self.detail is None and "detail" in self.model_fields_set:
            _dict['detail'] = None

        # set to None if action (nullable) is None
        # and model_fields_set contains the field
        if self.action is None and "action" in self.model_fields_set:
            _dict['action'] = None

        # set to None if previous_value (nullable) is None
        # and model_fields_set contains the field
        if self.previous_value is None and "previous_value" in self.model_fields_set:
            _dict['previousValue'] = None

        # set to None if new_value (nullable) is None
        # and model_fields_set contains the field
        if self.new_value is None and "new_value" in self.model_fields_set:
            _dict['newValue'] = None

        # set to None if sis_value (nullable) is None
        # and model_fields_set contains the field
        if self.sis_value is None and "sis_value" in self.model_fields_set:
            _dict['sisValue'] = None

        # set to None if overridden_by (nullable) is None
        # and model_fields_set contains the field
        if self.overridden_by is None and "overridden_by" in self.model_fields_set:
            _dict['overriddenBy'] = None

        # set to None if overridden_at (nullable) is None
        # and model_fields_set contains the field
        if self.overridden_at is None and "overridden_at" in self.model_fields_set:
            _dict['overriddenAt'] = None

        # set to None if acting_student_id (nullable) is None
        # and model_fields_set contains the field
        if self.acting_student_id is None and "acting_student_id" in self.model_fields_set:
            _dict['actingStudentId'] = None

        # set to None if student_ids (nullable) is None
        # and model_fields_set contains the field
        if self.student_ids is None and "student_ids" in self.model_fields_set:
            _dict['studentIds'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminContactOverrideHistoryEntryDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "eventId": obj.get("eventId"),
            "detail": obj.get("detail"),
            "action": obj.get("action"),
            "previousValue": obj.get("previousValue"),
            "newValue": obj.get("newValue"),
            "sisValue": obj.get("sisValue"),
            "overriddenBy": obj.get("overriddenBy"),
            "overriddenAt": obj.get("overriddenAt"),
            "actingStudentId": obj.get("actingStudentId"),
            "studentIds": obj.get("studentIds")
        })
        return _obj


