# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from edgraph_platform_client.models.ed_graph_http_aggregators_tenant_api_controllers_v1_view_models_requests_enrollment_admin_grade_capacity_request_dto import EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminGradeCapacityRequestDto
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateSchoolProgramRequestDto(BaseModel):
    """
    Covers two cases, distinguished by EdGraph.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Requests.EnrollmentAdmin.CreateSchoolProgramRequestDto.ProgramCatalogEntryId: adding an existing  district catalog entry to a school (a \"school association\" - EdGraph.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Requests.EnrollmentAdmin.CreateSchoolProgramRequestDto.Code/  EdGraph.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Requests.EnrollmentAdmin.CreateSchoolProgramRequestDto.Name/EdGraph.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Requests.EnrollmentAdmin.CreateSchoolProgramRequestDto.ProgramType/EdGraph.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Requests.EnrollmentAdmin.CreateSchoolProgramRequestDto.EligibilityCriteria/  EdGraph.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Requests.EnrollmentAdmin.CreateSchoolProgramRequestDto.RequiredDocuments are inherited and must be left unset), or creating a brand new  school-specific program (those same fields are required).
    """ # noqa: E501
    tenant_id: Optional[UUID] = Field(default=None, alias="tenantId")
    school_code: Optional[StrictStr] = Field(default=None, alias="schoolCode")
    school_name: Optional[StrictStr] = Field(default=None, alias="schoolName")
    program_catalog_entry_id: Optional[UUID] = Field(default=None, alias="programCatalogEntryId")
    code: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    program_type: Optional[StrictStr] = Field(default=None, alias="programType")
    eligibility_criteria: Optional[StrictStr] = Field(default=None, alias="eligibilityCriteria")
    required_documents: Optional[List[StrictStr]] = Field(default=None, alias="requiredDocuments")
    grades: Optional[List[StrictStr]] = None
    capacity_by_grade: Optional[List[EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminGradeCapacityRequestDto]] = Field(default=None, alias="capacityByGrade")
    zone: Optional[StrictStr] = None
    latitude: Optional[Union[StrictFloat, StrictInt]] = None
    longitude: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["tenantId", "schoolCode", "schoolName", "programCatalogEntryId", "code", "name", "programType", "eligibilityCriteria", "requiredDocuments", "grades", "capacityByGrade", "zone", "latitude", "longitude"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateSchoolProgramRequestDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in capacity_by_grade (list)
        _items = []
        if self.capacity_by_grade:
            for _item_capacity_by_grade in self.capacity_by_grade:
                if _item_capacity_by_grade:
                    _items.append(_item_capacity_by_grade.to_dict())
            _dict['capacityByGrade'] = _items
        # set to None if school_code (nullable) is None
        # and model_fields_set contains the field
        if self.school_code is None and "school_code" in self.model_fields_set:
            _dict['schoolCode'] = None

        # set to None if school_name (nullable) is None
        # and model_fields_set contains the field
        if self.school_name is None and "school_name" in self.model_fields_set:
            _dict['schoolName'] = None

        # set to None if program_catalog_entry_id (nullable) is None
        # and model_fields_set contains the field
        if self.program_catalog_entry_id is None and "program_catalog_entry_id" in self.model_fields_set:
            _dict['programCatalogEntryId'] = None

        # set to None if code (nullable) is None
        # and model_fields_set contains the field
        if self.code is None and "code" in self.model_fields_set:
            _dict['code'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if program_type (nullable) is None
        # and model_fields_set contains the field
        if self.program_type is None and "program_type" in self.model_fields_set:
            _dict['programType'] = None

        # set to None if eligibility_criteria (nullable) is None
        # and model_fields_set contains the field
        if self.eligibility_criteria is None and "eligibility_criteria" in self.model_fields_set:
            _dict['eligibilityCriteria'] = None

        # set to None if required_documents (nullable) is None
        # and model_fields_set contains the field
        if self.required_documents is None and "required_documents" in self.model_fields_set:
            _dict['requiredDocuments'] = None

        # set to None if grades (nullable) is None
        # and model_fields_set contains the field
        if self.grades is None and "grades" in self.model_fields_set:
            _dict['grades'] = None

        # set to None if capacity_by_grade (nullable) is None
        # and model_fields_set contains the field
        if self.capacity_by_grade is None and "capacity_by_grade" in self.model_fields_set:
            _dict['capacityByGrade'] = None

        # set to None if zone (nullable) is None
        # and model_fields_set contains the field
        if self.zone is None and "zone" in self.model_fields_set:
            _dict['zone'] = None

        # set to None if latitude (nullable) is None
        # and model_fields_set contains the field
        if self.latitude is None and "latitude" in self.model_fields_set:
            _dict['latitude'] = None

        # set to None if longitude (nullable) is None
        # and model_fields_set contains the field
        if self.longitude is None and "longitude" in self.model_fields_set:
            _dict['longitude'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateSchoolProgramRequestDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tenantId": obj.get("tenantId"),
            "schoolCode": obj.get("schoolCode"),
            "schoolName": obj.get("schoolName"),
            "programCatalogEntryId": obj.get("programCatalogEntryId"),
            "code": obj.get("code"),
            "name": obj.get("name"),
            "programType": obj.get("programType"),
            "eligibilityCriteria": obj.get("eligibilityCriteria"),
            "requiredDocuments": obj.get("requiredDocuments"),
            "grades": obj.get("grades"),
            "capacityByGrade": [EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminGradeCapacityRequestDto.from_dict(_item) for _item in obj["capacityByGrade"]] if obj.get("capacityByGrade") is not None else None,
            "zone": obj.get("zone"),
            "latitude": obj.get("latitude"),
            "longitude": obj.get("longitude")
        })
        return _obj


