# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateProgramCatalogEntryRequestDto(BaseModel):
    """
    The body of a district catalog entry creation. No school-identifying field - that is what  distinguishes a catalog entry from a school program; see  EdGraph.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Requests.EnrollmentAdmin.CreateSchoolProgramRequestDto for adding it to a school.
    """ # noqa: E501
    tenant_id: Optional[UUID] = Field(default=None, alias="tenantId")
    code: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    program_type: Optional[StrictStr] = Field(default=None, alias="programType")
    eligibility_criteria: Optional[StrictStr] = Field(default=None, alias="eligibilityCriteria")
    required_documents: Optional[List[StrictStr]] = Field(default=None, alias="requiredDocuments")
    internal_display_name: Optional[StrictStr] = Field(default=None, alias="internalDisplayName")
    __properties: ClassVar[List[str]] = ["tenantId", "code", "name", "programType", "eligibilityCriteria", "requiredDocuments", "internalDisplayName"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateProgramCatalogEntryRequestDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if code (nullable) is None
        # and model_fields_set contains the field
        if self.code is None and "code" in self.model_fields_set:
            _dict['code'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if program_type (nullable) is None
        # and model_fields_set contains the field
        if self.program_type is None and "program_type" in self.model_fields_set:
            _dict['programType'] = None

        # set to None if eligibility_criteria (nullable) is None
        # and model_fields_set contains the field
        if self.eligibility_criteria is None and "eligibility_criteria" in self.model_fields_set:
            _dict['eligibilityCriteria'] = None

        # set to None if required_documents (nullable) is None
        # and model_fields_set contains the field
        if self.required_documents is None and "required_documents" in self.model_fields_set:
            _dict['requiredDocuments'] = None

        # set to None if internal_display_name (nullable) is None
        # and model_fields_set contains the field
        if self.internal_display_name is None and "internal_display_name" in self.model_fields_set:
            _dict['internalDisplayName'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateProgramCatalogEntryRequestDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tenantId": obj.get("tenantId"),
            "code": obj.get("code"),
            "name": obj.get("name"),
            "programType": obj.get("programType"),
            "eligibilityCriteria": obj.get("eligibilityCriteria"),
            "requiredDocuments": obj.get("requiredDocuments"),
            "internalDisplayName": obj.get("internalDisplayName")
        })
        return _obj


