# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from edgraph_platform_client.models.ed_graph_http_aggregators_tenant_api_controllers_v1_view_models_responses_enrollment_admin_contact_student_response_dto import EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminContactStudentResponseDto
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminContactResponseDto(BaseModel):
    """
    EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminContactResponseDto
    """ # noqa: E501
    id: Optional[UUID] = None
    tenant_id: Optional[UUID] = Field(default=None, alias="tenantId")
    external_data_source_contact_id: Optional[StrictStr] = Field(default=None, alias="externalDataSourceContactId")
    first_name: Optional[StrictStr] = Field(default=None, alias="firstName")
    last_name: Optional[StrictStr] = Field(default=None, alias="lastName")
    email: Optional[StrictStr] = None
    phone: Optional[StrictStr] = None
    students: Optional[List[EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminContactStudentResponseDto]] = None
    relationship: Optional[StrictStr] = None
    student_count: Optional[StrictInt] = Field(default=None, alias="studentCount")
    student_local_codes: Optional[List[StrictStr]] = Field(default=None, alias="studentLocalCodes")
    is_phone_override: Optional[StrictBool] = Field(default=None, alias="isPhoneOverride")
    is_email_override: Optional[StrictBool] = Field(default=None, alias="isEmailOverride")
    sis_email: Optional[StrictStr] = Field(default=None, alias="sisEmail")
    sis_phone: Optional[StrictStr] = Field(default=None, alias="sisPhone")
    email_last_overridden_by: Optional[StrictStr] = Field(default=None, alias="emailLastOverriddenBy")
    email_last_overridden_date_time: Optional[datetime] = Field(default=None, alias="emailLastOverriddenDateTime")
    phone_last_overridden_by: Optional[StrictStr] = Field(default=None, alias="phoneLastOverriddenBy")
    phone_last_overridden_date_time: Optional[datetime] = Field(default=None, alias="phoneLastOverriddenDateTime")
    sign_in_status: Optional[StrictStr] = Field(default=None, alias="signInStatus")
    is_locked: Optional[StrictBool] = Field(default=None, alias="isLocked")
    created_by: Optional[StrictStr] = Field(default=None, alias="createdBy")
    created_date_time: Optional[datetime] = Field(default=None, alias="createdDateTime")
    last_modified_by: Optional[StrictStr] = Field(default=None, alias="lastModifiedBy")
    last_modified_date_time: Optional[datetime] = Field(default=None, alias="lastModifiedDateTime")
    last_updated_date_time: Optional[datetime] = Field(default=None, alias="lastUpdatedDateTime")
    deleted_by: Optional[StrictStr] = Field(default=None, alias="deletedBy")
    deleted_date_time: Optional[datetime] = Field(default=None, alias="deletedDateTime")
    is_deleted: Optional[StrictBool] = Field(default=None, alias="isDeleted")
    verification_status: Optional[StrictStr] = Field(default=None, alias="verificationStatus")
    __properties: ClassVar[List[str]] = ["id", "tenantId", "externalDataSourceContactId", "firstName", "lastName", "email", "phone", "students", "relationship", "studentCount", "studentLocalCodes", "isPhoneOverride", "isEmailOverride", "sisEmail", "sisPhone", "emailLastOverriddenBy", "emailLastOverriddenDateTime", "phoneLastOverriddenBy", "phoneLastOverriddenDateTime", "signInStatus", "isLocked", "createdBy", "createdDateTime", "lastModifiedBy", "lastModifiedDateTime", "lastUpdatedDateTime", "deletedBy", "deletedDateTime", "isDeleted", "verificationStatus"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminContactResponseDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in students (list)
        _items = []
        if self.students:
            for _item_students in self.students:
                if _item_students:
                    _items.append(_item_students.to_dict())
            _dict['students'] = _items
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if tenant_id (nullable) is None
        # and model_fields_set contains the field
        if self.tenant_id is None and "tenant_id" in self.model_fields_set:
            _dict['tenantId'] = None

        # set to None if external_data_source_contact_id (nullable) is None
        # and model_fields_set contains the field
        if self.external_data_source_contact_id is None and "external_data_source_contact_id" in self.model_fields_set:
            _dict['externalDataSourceContactId'] = None

        # set to None if first_name (nullable) is None
        # and model_fields_set contains the field
        if self.first_name is None and "first_name" in self.model_fields_set:
            _dict['firstName'] = None

        # set to None if last_name (nullable) is None
        # and model_fields_set contains the field
        if self.last_name is None and "last_name" in self.model_fields_set:
            _dict['lastName'] = None

        # set to None if email (nullable) is None
        # and model_fields_set contains the field
        if self.email is None and "email" in self.model_fields_set:
            _dict['email'] = None

        # set to None if phone (nullable) is None
        # and model_fields_set contains the field
        if self.phone is None and "phone" in self.model_fields_set:
            _dict['phone'] = None

        # set to None if students (nullable) is None
        # and model_fields_set contains the field
        if self.students is None and "students" in self.model_fields_set:
            _dict['students'] = None

        # set to None if relationship (nullable) is None
        # and model_fields_set contains the field
        if self.relationship is None and "relationship" in self.model_fields_set:
            _dict['relationship'] = None

        # set to None if student_local_codes (nullable) is None
        # and model_fields_set contains the field
        if self.student_local_codes is None and "student_local_codes" in self.model_fields_set:
            _dict['studentLocalCodes'] = None

        # set to None if is_phone_override (nullable) is None
        # and model_fields_set contains the field
        if self.is_phone_override is None and "is_phone_override" in self.model_fields_set:
            _dict['isPhoneOverride'] = None

        # set to None if is_email_override (nullable) is None
        # and model_fields_set contains the field
        if self.is_email_override is None and "is_email_override" in self.model_fields_set:
            _dict['isEmailOverride'] = None

        # set to None if sis_email (nullable) is None
        # and model_fields_set contains the field
        if self.sis_email is None and "sis_email" in self.model_fields_set:
            _dict['sisEmail'] = None

        # set to None if sis_phone (nullable) is None
        # and model_fields_set contains the field
        if self.sis_phone is None and "sis_phone" in self.model_fields_set:
            _dict['sisPhone'] = None

        # set to None if email_last_overridden_by (nullable) is None
        # and model_fields_set contains the field
        if self.email_last_overridden_by is None and "email_last_overridden_by" in self.model_fields_set:
            _dict['emailLastOverriddenBy'] = None

        # set to None if email_last_overridden_date_time (nullable) is None
        # and model_fields_set contains the field
        if self.email_last_overridden_date_time is None and "email_last_overridden_date_time" in self.model_fields_set:
            _dict['emailLastOverriddenDateTime'] = None

        # set to None if phone_last_overridden_by (nullable) is None
        # and model_fields_set contains the field
        if self.phone_last_overridden_by is None and "phone_last_overridden_by" in self.model_fields_set:
            _dict['phoneLastOverriddenBy'] = None

        # set to None if phone_last_overridden_date_time (nullable) is None
        # and model_fields_set contains the field
        if self.phone_last_overridden_date_time is None and "phone_last_overridden_date_time" in self.model_fields_set:
            _dict['phoneLastOverriddenDateTime'] = None

        # set to None if sign_in_status (nullable) is None
        # and model_fields_set contains the field
        if self.sign_in_status is None and "sign_in_status" in self.model_fields_set:
            _dict['signInStatus'] = None

        # set to None if created_by (nullable) is None
        # and model_fields_set contains the field
        if self.created_by is None and "created_by" in self.model_fields_set:
            _dict['createdBy'] = None

        # set to None if created_date_time (nullable) is None
        # and model_fields_set contains the field
        if self.created_date_time is None and "created_date_time" in self.model_fields_set:
            _dict['createdDateTime'] = None

        # set to None if last_modified_by (nullable) is None
        # and model_fields_set contains the field
        if self.last_modified_by is None and "last_modified_by" in self.model_fields_set:
            _dict['lastModifiedBy'] = None

        # set to None if last_modified_date_time (nullable) is None
        # and model_fields_set contains the field
        if self.last_modified_date_time is None and "last_modified_date_time" in self.model_fields_set:
            _dict['lastModifiedDateTime'] = None

        # set to None if last_updated_date_time (nullable) is None
        # and model_fields_set contains the field
        if self.last_updated_date_time is None and "last_updated_date_time" in self.model_fields_set:
            _dict['lastUpdatedDateTime'] = None

        # set to None if deleted_by (nullable) is None
        # and model_fields_set contains the field
        if self.deleted_by is None and "deleted_by" in self.model_fields_set:
            _dict['deletedBy'] = None

        # set to None if deleted_date_time (nullable) is None
        # and model_fields_set contains the field
        if self.deleted_date_time is None and "deleted_date_time" in self.model_fields_set:
            _dict['deletedDateTime'] = None

        # set to None if verification_status (nullable) is None
        # and model_fields_set contains the field
        if self.verification_status is None and "verification_status" in self.model_fields_set:
            _dict['verificationStatus'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminContactResponseDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "tenantId": obj.get("tenantId"),
            "externalDataSourceContactId": obj.get("externalDataSourceContactId"),
            "firstName": obj.get("firstName"),
            "lastName": obj.get("lastName"),
            "email": obj.get("email"),
            "phone": obj.get("phone"),
            "students": [EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminContactStudentResponseDto.from_dict(_item) for _item in obj["students"]] if obj.get("students") is not None else None,
            "relationship": obj.get("relationship"),
            "studentCount": obj.get("studentCount"),
            "studentLocalCodes": obj.get("studentLocalCodes"),
            "isPhoneOverride": obj.get("isPhoneOverride"),
            "isEmailOverride": obj.get("isEmailOverride"),
            "sisEmail": obj.get("sisEmail"),
            "sisPhone": obj.get("sisPhone"),
            "emailLastOverriddenBy": obj.get("emailLastOverriddenBy"),
            "emailLastOverriddenDateTime": obj.get("emailLastOverriddenDateTime"),
            "phoneLastOverriddenBy": obj.get("phoneLastOverriddenBy"),
            "phoneLastOverriddenDateTime": obj.get("phoneLastOverriddenDateTime"),
            "signInStatus": obj.get("signInStatus"),
            "isLocked": obj.get("isLocked"),
            "createdBy": obj.get("createdBy"),
            "createdDateTime": obj.get("createdDateTime"),
            "lastModifiedBy": obj.get("lastModifiedBy"),
            "lastModifiedDateTime": obj.get("lastModifiedDateTime"),
            "lastUpdatedDateTime": obj.get("lastUpdatedDateTime"),
            "deletedBy": obj.get("deletedBy"),
            "deletedDateTime": obj.get("deletedDateTime"),
            "isDeleted": obj.get("isDeleted"),
            "verificationStatus": obj.get("verificationStatus")
        })
        return _obj


