# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EdfiAdminApiEdfiAdminV1ClaimSetDetailsResourceClaim(BaseModel):
    """
    EdfiAdminApiEdfiAdminV1ClaimSetDetailsResourceClaim
    """ # noqa: E501
    resource_claim_id: Optional[StrictInt] = Field(default=None, alias="resourceClaimId")
    name: Optional[StrictStr] = None
    create: Optional[StrictBool] = None
    create_auth_strategy: Optional[StrictStr] = Field(default=None, alias="createAuthStrategy")
    create_auth_strategy_override: Optional[StrictStr] = Field(default=None, alias="createAuthStrategyOverride")
    read: Optional[StrictBool] = None
    read_auth_strategy: Optional[StrictStr] = Field(default=None, alias="readAuthStrategy")
    read_auth_strategy_override: Optional[StrictStr] = Field(default=None, alias="readAuthStrategyOverride")
    update: Optional[StrictBool] = None
    update_auth_strategy: Optional[StrictStr] = Field(default=None, alias="updateAuthStrategy")
    update_auth_strategy_override: Optional[StrictStr] = Field(default=None, alias="updateAuthStrategyOverride")
    delete: Optional[StrictBool] = None
    delete_auth_strategy: Optional[StrictStr] = Field(default=None, alias="deleteAuthStrategy")
    delete_auth_strategy_override: Optional[StrictStr] = Field(default=None, alias="deleteAuthStrategyOverride")
    children: Optional[List[EdfiAdminApiEdfiAdminV1ClaimSetDetailsResourceClaim]] = None
    read_changes: Optional[StrictBool] = Field(default=None, alias="readChanges")
    read_changes_auth_strategy: Optional[StrictStr] = Field(default=None, alias="readChangesAuthStrategy")
    read_changes_auth_strategy_override: Optional[StrictStr] = Field(default=None, alias="readChangesAuthStrategyOverride")
    __properties: ClassVar[List[str]] = ["resourceClaimId", "name", "create", "createAuthStrategy", "createAuthStrategyOverride", "read", "readAuthStrategy", "readAuthStrategyOverride", "update", "updateAuthStrategy", "updateAuthStrategyOverride", "delete", "deleteAuthStrategy", "deleteAuthStrategyOverride", "children", "readChanges", "readChangesAuthStrategy", "readChangesAuthStrategyOverride"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EdfiAdminApiEdfiAdminV1ClaimSetDetailsResourceClaim from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "children",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in children (list)
        _items = []
        if self.children:
            for _item_children in self.children:
                if _item_children:
                    _items.append(_item_children.to_dict())
            _dict['children'] = _items
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if create_auth_strategy (nullable) is None
        # and model_fields_set contains the field
        if self.create_auth_strategy is None and "create_auth_strategy" in self.model_fields_set:
            _dict['createAuthStrategy'] = None

        # set to None if create_auth_strategy_override (nullable) is None
        # and model_fields_set contains the field
        if self.create_auth_strategy_override is None and "create_auth_strategy_override" in self.model_fields_set:
            _dict['createAuthStrategyOverride'] = None

        # set to None if read_auth_strategy (nullable) is None
        # and model_fields_set contains the field
        if self.read_auth_strategy is None and "read_auth_strategy" in self.model_fields_set:
            _dict['readAuthStrategy'] = None

        # set to None if read_auth_strategy_override (nullable) is None
        # and model_fields_set contains the field
        if self.read_auth_strategy_override is None and "read_auth_strategy_override" in self.model_fields_set:
            _dict['readAuthStrategyOverride'] = None

        # set to None if update_auth_strategy (nullable) is None
        # and model_fields_set contains the field
        if self.update_auth_strategy is None and "update_auth_strategy" in self.model_fields_set:
            _dict['updateAuthStrategy'] = None

        # set to None if update_auth_strategy_override (nullable) is None
        # and model_fields_set contains the field
        if self.update_auth_strategy_override is None and "update_auth_strategy_override" in self.model_fields_set:
            _dict['updateAuthStrategyOverride'] = None

        # set to None if delete_auth_strategy (nullable) is None
        # and model_fields_set contains the field
        if self.delete_auth_strategy is None and "delete_auth_strategy" in self.model_fields_set:
            _dict['deleteAuthStrategy'] = None

        # set to None if delete_auth_strategy_override (nullable) is None
        # and model_fields_set contains the field
        if self.delete_auth_strategy_override is None and "delete_auth_strategy_override" in self.model_fields_set:
            _dict['deleteAuthStrategyOverride'] = None

        # set to None if children (nullable) is None
        # and model_fields_set contains the field
        if self.children is None and "children" in self.model_fields_set:
            _dict['children'] = None

        # set to None if read_changes_auth_strategy (nullable) is None
        # and model_fields_set contains the field
        if self.read_changes_auth_strategy is None and "read_changes_auth_strategy" in self.model_fields_set:
            _dict['readChangesAuthStrategy'] = None

        # set to None if read_changes_auth_strategy_override (nullable) is None
        # and model_fields_set contains the field
        if self.read_changes_auth_strategy_override is None and "read_changes_auth_strategy_override" in self.model_fields_set:
            _dict['readChangesAuthStrategyOverride'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EdfiAdminApiEdfiAdminV1ClaimSetDetailsResourceClaim from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "resourceClaimId": obj.get("resourceClaimId"),
            "name": obj.get("name"),
            "create": obj.get("create"),
            "createAuthStrategy": obj.get("createAuthStrategy"),
            "createAuthStrategyOverride": obj.get("createAuthStrategyOverride"),
            "read": obj.get("read"),
            "readAuthStrategy": obj.get("readAuthStrategy"),
            "readAuthStrategyOverride": obj.get("readAuthStrategyOverride"),
            "update": obj.get("update"),
            "updateAuthStrategy": obj.get("updateAuthStrategy"),
            "updateAuthStrategyOverride": obj.get("updateAuthStrategyOverride"),
            "delete": obj.get("delete"),
            "deleteAuthStrategy": obj.get("deleteAuthStrategy"),
            "deleteAuthStrategyOverride": obj.get("deleteAuthStrategyOverride"),
            "children": [EdfiAdminApiEdfiAdminV1ClaimSetDetailsResourceClaim.from_dict(_item) for _item in obj["children"]] if obj.get("children") is not None else None,
            "readChanges": obj.get("readChanges"),
            "readChangesAuthStrategy": obj.get("readChangesAuthStrategy"),
            "readChangesAuthStrategyOverride": obj.get("readChangesAuthStrategyOverride")
        })
        return _obj

# TODO: Rewrite to not use raise_errors
EdfiAdminApiEdfiAdminV1ClaimSetDetailsResourceClaim.model_rebuild(raise_errors=False)

