# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class IdentityApiUserV1TenantType(str, Enum):
    """
    IdentityApiUserV1TenantType
    """

    """
    allowed enum values
    """
    UNKNOWN = 'Unknown'
    DATASTANDARDGOVERNINGBODY = 'DataStandardGoverningBody'
    EDUCATIONALSERVICEAGENCY = 'EducationalServiceAgency'
    IMPLEMENTATIONPARTNER = 'ImplementationPartner'
    INDEPENDENTSOFTWAREVENDOR = 'IndependentSoftwareVendor'
    INTERNAL = 'Internal'
    LOCALEDUCATIONAGENCY = 'LocalEducationAgency'
    MANAGEDSERVICEPROVIDER = 'ManagedServiceProvider'
    STATEEDUCATIONAGENCY = 'StateEducationAgency'
    ASSESSMENTPROVIDER = 'AssessmentProvider'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of IdentityApiUserV1TenantType from a JSON string"""
        return cls(json.loads(json_str))


