# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from edgraph_platform_client.models.registration_api_registration_v2_tenant_type import RegistrationApiRegistrationV2TenantType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RegistrationApiRegistrationV2SubmitTenantRegistrationRequest(BaseModel):
    """
    RegistrationApiRegistrationV2SubmitTenantRegistrationRequest
    """ # noqa: E501
    tenant_types: Optional[List[RegistrationApiRegistrationV2TenantType]] = Field(default=None, alias="tenantTypes")
    first_name: Optional[StrictStr] = Field(default=None, alias="firstName")
    last_name: Optional[StrictStr] = Field(default=None, alias="lastName")
    email: Optional[StrictStr] = None
    state: Optional[StrictStr] = None
    organization_identifier: Optional[StrictStr] = Field(default=None, alias="organizationIdentifier")
    organization_name: Optional[StrictStr] = Field(default=None, alias="organizationName")
    password: Optional[StrictStr] = None
    application_ids: Optional[List[StrictStr]] = Field(default=None, alias="applicationIds")
    azure_subscription_id: Optional[StrictStr] = Field(default=None, alias="azureSubscriptionId")
    azure_subscription_storage_path: Optional[StrictStr] = Field(default=None, alias="azureSubscriptionStoragePath")
    __properties: ClassVar[List[str]] = ["tenantTypes", "firstName", "lastName", "email", "state", "organizationIdentifier", "organizationName", "password", "applicationIds", "azureSubscriptionId", "azureSubscriptionStoragePath"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RegistrationApiRegistrationV2SubmitTenantRegistrationRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "tenant_types",
            "application_ids",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if tenant_types (nullable) is None
        # and model_fields_set contains the field
        if self.tenant_types is None and "tenant_types" in self.model_fields_set:
            _dict['tenantTypes'] = None

        # set to None if first_name (nullable) is None
        # and model_fields_set contains the field
        if self.first_name is None and "first_name" in self.model_fields_set:
            _dict['firstName'] = None

        # set to None if last_name (nullable) is None
        # and model_fields_set contains the field
        if self.last_name is None and "last_name" in self.model_fields_set:
            _dict['lastName'] = None

        # set to None if email (nullable) is None
        # and model_fields_set contains the field
        if self.email is None and "email" in self.model_fields_set:
            _dict['email'] = None

        # set to None if state (nullable) is None
        # and model_fields_set contains the field
        if self.state is None and "state" in self.model_fields_set:
            _dict['state'] = None

        # set to None if organization_identifier (nullable) is None
        # and model_fields_set contains the field
        if self.organization_identifier is None and "organization_identifier" in self.model_fields_set:
            _dict['organizationIdentifier'] = None

        # set to None if organization_name (nullable) is None
        # and model_fields_set contains the field
        if self.organization_name is None and "organization_name" in self.model_fields_set:
            _dict['organizationName'] = None

        # set to None if password (nullable) is None
        # and model_fields_set contains the field
        if self.password is None and "password" in self.model_fields_set:
            _dict['password'] = None

        # set to None if application_ids (nullable) is None
        # and model_fields_set contains the field
        if self.application_ids is None and "application_ids" in self.model_fields_set:
            _dict['applicationIds'] = None

        # set to None if azure_subscription_id (nullable) is None
        # and model_fields_set contains the field
        if self.azure_subscription_id is None and "azure_subscription_id" in self.model_fields_set:
            _dict['azureSubscriptionId'] = None

        # set to None if azure_subscription_storage_path (nullable) is None
        # and model_fields_set contains the field
        if self.azure_subscription_storage_path is None and "azure_subscription_storage_path" in self.model_fields_set:
            _dict['azureSubscriptionStoragePath'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RegistrationApiRegistrationV2SubmitTenantRegistrationRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tenantTypes": obj.get("tenantTypes"),
            "firstName": obj.get("firstName"),
            "lastName": obj.get("lastName"),
            "email": obj.get("email"),
            "state": obj.get("state"),
            "organizationIdentifier": obj.get("organizationIdentifier"),
            "organizationName": obj.get("organizationName"),
            "password": obj.get("password"),
            "applicationIds": obj.get("applicationIds"),
            "azureSubscriptionId": obj.get("azureSubscriptionId"),
            "azureSubscriptionStoragePath": obj.get("azureSubscriptionStoragePath")
        })
        return _obj


