# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from edgraph_platform_client.models.tenant_api_webhook_v1_webhook_re_run_strategy import TenantApiWebhookV1WebhookReRunStrategy
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TenantApiWebhookV1RequestReRunRequest(BaseModel):
    """
    TenantApiWebhookV1RequestReRunRequest
    """ # noqa: E501
    tenant_id: Optional[StrictStr] = Field(default=None, alias="tenantId")
    webhook_id: Optional[StrictStr] = Field(default=None, alias="webhookId")
    dispatch_id: Optional[StrictStr] = Field(default=None, alias="dispatchId")
    webhook_re_run_strategy: Optional[TenantApiWebhookV1WebhookReRunStrategy] = Field(default=None, alias="webhookReRunStrategy")
    __properties: ClassVar[List[str]] = ["tenantId", "webhookId", "dispatchId", "webhookReRunStrategy"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TenantApiWebhookV1RequestReRunRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if tenant_id (nullable) is None
        # and model_fields_set contains the field
        if self.tenant_id is None and "tenant_id" in self.model_fields_set:
            _dict['tenantId'] = None

        # set to None if webhook_id (nullable) is None
        # and model_fields_set contains the field
        if self.webhook_id is None and "webhook_id" in self.model_fields_set:
            _dict['webhookId'] = None

        # set to None if dispatch_id (nullable) is None
        # and model_fields_set contains the field
        if self.dispatch_id is None and "dispatch_id" in self.model_fields_set:
            _dict['dispatchId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TenantApiWebhookV1RequestReRunRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tenantId": obj.get("tenantId"),
            "webhookId": obj.get("webhookId"),
            "dispatchId": obj.get("dispatchId"),
            "webhookReRunStrategy": obj.get("webhookReRunStrategy")
        })
        return _obj


