# coding: utf-8

"""
    Tenant Api

    Tenant Api - v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.identity_api_staff_classification_v1_staff_classification_created_response import IdentityApiStaffClassificationV1StaffClassificationCreatedResponse

class TestIdentityApiStaffClassificationV1StaffClassificationCreatedResponse(unittest.TestCase):
    """IdentityApiStaffClassificationV1StaffClassificationCreatedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IdentityApiStaffClassificationV1StaffClassificationCreatedResponse:
        """Test IdentityApiStaffClassificationV1StaffClassificationCreatedResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IdentityApiStaffClassificationV1StaffClassificationCreatedResponse`
        """
        model = IdentityApiStaffClassificationV1StaffClassificationCreatedResponse()
        if include_optional:
            return IdentityApiStaffClassificationV1StaffClassificationCreatedResponse(
                id = ''
            )
        else:
            return IdentityApiStaffClassificationV1StaffClassificationCreatedResponse(
        )
        """

    def testIdentityApiStaffClassificationV1StaffClassificationCreatedResponse(self):
        """Test IdentityApiStaffClassificationV1StaffClassificationCreatedResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
