# coding: utf-8

"""
    Tenant Api

    Tenant Api - v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.identity_api_user_v1_password_resetted_response import IdentityApiUserV1PasswordResettedResponse

class TestIdentityApiUserV1PasswordResettedResponse(unittest.TestCase):
    """IdentityApiUserV1PasswordResettedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IdentityApiUserV1PasswordResettedResponse:
        """Test IdentityApiUserV1PasswordResettedResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IdentityApiUserV1PasswordResettedResponse`
        """
        model = IdentityApiUserV1PasswordResettedResponse()
        if include_optional:
            return IdentityApiUserV1PasswordResettedResponse(
                tenant_id = '',
                user_id = '',
                password = '',
                auto_generated_password = True
            )
        else:
            return IdentityApiUserV1PasswordResettedResponse(
        )
        """

    def testIdentityApiUserV1PasswordResettedResponse(self):
        """Test IdentityApiUserV1PasswordResettedResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
