# coding: utf-8

"""
    Tenant Api

    Tenant Api - v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edgraph_platform_client.models.ed_graph_http_aggregators_tenant_api_controllers_v1_view_models_responses_role import EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesRole

class TestEdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesRole(unittest.TestCase):
    """EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesRole:
        """Test EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesRole
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesRole`
        """
        model = EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesRole()
        if include_optional:
            return EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesRole(
                role_name = '',
                is_default = True,
                is_available_for_tenants = True,
                display_name = '',
                description = '',
                sort_order = 56
            )
        else:
            return EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesRole(
        )
        """

    def testEdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesRole(self):
        """Test EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesRole"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
