# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from edgraph_platform_client.models.identity_api_api_client_v1_api_claim import IdentityApiApiClientV1ApiClaim
from typing import Optional, Set
from typing_extensions import Self

class IdentityApiApiClientV1UpdateApiClientRequest(BaseModel):
    """
    IdentityApiApiClientV1UpdateApiClientRequest
    """ # noqa: E501
    tenant_id: Optional[StrictStr] = Field(default=None, alias="tenantId")
    client_id: Optional[StrictStr] = Field(default=None, alias="clientId")
    client_name: Optional[StrictStr] = Field(default=None, alias="clientName")
    enabled: Optional[StrictBool] = None
    api_claims: Optional[List[IdentityApiApiClientV1ApiClaim]] = Field(default=None, alias="apiClaims")
    __properties: ClassVar[List[str]] = ["tenantId", "clientId", "clientName", "enabled", "apiClaims"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IdentityApiApiClientV1UpdateApiClientRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "api_claims",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in api_claims (list)
        _items = []
        if self.api_claims:
            for _item_api_claims in self.api_claims:
                if _item_api_claims:
                    _items.append(_item_api_claims.to_dict())
            _dict['apiClaims'] = _items
        # set to None if tenant_id (nullable) is None
        # and model_fields_set contains the field
        if self.tenant_id is None and "tenant_id" in self.model_fields_set:
            _dict['tenantId'] = None

        # set to None if client_id (nullable) is None
        # and model_fields_set contains the field
        if self.client_id is None and "client_id" in self.model_fields_set:
            _dict['clientId'] = None

        # set to None if client_name (nullable) is None
        # and model_fields_set contains the field
        if self.client_name is None and "client_name" in self.model_fields_set:
            _dict['clientName'] = None

        # set to None if api_claims (nullable) is None
        # and model_fields_set contains the field
        if self.api_claims is None and "api_claims" in self.model_fields_set:
            _dict['apiClaims'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IdentityApiApiClientV1UpdateApiClientRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tenantId": obj.get("tenantId"),
            "clientId": obj.get("clientId"),
            "clientName": obj.get("clientName"),
            "enabled": obj.get("enabled"),
            "apiClaims": [IdentityApiApiClientV1ApiClaim.from_dict(_item) for _item in obj["apiClaims"]] if obj.get("apiClaims") is not None else None
        })
        return _obj


