# coding: utf-8

"""
    Tenant Api

    Tenant Api - v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class IdentityApiUserV1AddSectionBulkRequestTypesSectionDto(BaseModel):
    """
    IdentityApiUserV1AddSectionBulkRequestTypesSectionDto
    """ # noqa: E501
    education_organization_id: Optional[StrictInt] = Field(default=None, alias="educationOrganizationId")
    section_id: Optional[StrictStr] = Field(default=None, alias="sectionId")
    staff_unique_id: Optional[StrictStr] = Field(default=None, alias="staffUniqueId")
    classroom_position_descriptor: Optional[StrictStr] = Field(default=None, alias="classroomPositionDescriptor")
    begin_date: Optional[StrictStr] = Field(default=None, alias="beginDate")
    end_date: Optional[StrictStr] = Field(default=None, alias="endDate")
    source: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["educationOrganizationId", "sectionId", "staffUniqueId", "classroomPositionDescriptor", "beginDate", "endDate", "source"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IdentityApiUserV1AddSectionBulkRequestTypesSectionDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if section_id (nullable) is None
        # and model_fields_set contains the field
        if self.section_id is None and "section_id" in self.model_fields_set:
            _dict['sectionId'] = None

        # set to None if staff_unique_id (nullable) is None
        # and model_fields_set contains the field
        if self.staff_unique_id is None and "staff_unique_id" in self.model_fields_set:
            _dict['staffUniqueId'] = None

        # set to None if classroom_position_descriptor (nullable) is None
        # and model_fields_set contains the field
        if self.classroom_position_descriptor is None and "classroom_position_descriptor" in self.model_fields_set:
            _dict['classroomPositionDescriptor'] = None

        # set to None if begin_date (nullable) is None
        # and model_fields_set contains the field
        if self.begin_date is None and "begin_date" in self.model_fields_set:
            _dict['beginDate'] = None

        # set to None if end_date (nullable) is None
        # and model_fields_set contains the field
        if self.end_date is None and "end_date" in self.model_fields_set:
            _dict['endDate'] = None

        # set to None if source (nullable) is None
        # and model_fields_set contains the field
        if self.source is None and "source" in self.model_fields_set:
            _dict['source'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IdentityApiUserV1AddSectionBulkRequestTypesSectionDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "educationOrganizationId": obj.get("educationOrganizationId"),
            "sectionId": obj.get("sectionId"),
            "staffUniqueId": obj.get("staffUniqueId"),
            "classroomPositionDescriptor": obj.get("classroomPositionDescriptor"),
            "beginDate": obj.get("beginDate"),
            "endDate": obj.get("endDate"),
            "source": obj.get("source")
        })
        return _obj


