# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class IdentityApiUserV1RevokeStrategy(str, Enum):
    """
    IdentityApiUserV1RevokeStrategy
    """

    """
    allowed enum values
    """
    UNKNOWN = 'Unknown'
    REVOKEIMPLICIT = 'RevokeImplicit'
    REVOKEEXPLICIT = 'RevokeExplicit'
    UNDOEXPLICITREVOKE = 'UndoExplicitRevoke'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of IdentityApiUserV1RevokeStrategy from a JSON string"""
        return cls(json.loads(json_str))


