# coding: utf-8

"""
    All Api

    All Api- v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from edgraph_platform_client.models.tenant_api_partnership_v1_tenant_type import TenantApiPartnershipV1TenantType
from typing import Optional, Set
from typing_extensions import Self

class TenantApiPartnershipV1ParternshipTenantResponse(BaseModel):
    """
    TenantApiPartnershipV1ParternshipTenantResponse
    """ # noqa: E501
    tenant_id: Optional[StrictStr] = Field(default=None, alias="tenantId")
    tenant_types: Optional[List[TenantApiPartnershipV1TenantType]] = Field(default=None, alias="tenantTypes")
    organization_identifier: Optional[StrictStr] = Field(default=None, alias="organizationIdentifier")
    organization_name: Optional[StrictStr] = Field(default=None, alias="organizationName")
    created_date_time: Optional[StrictStr] = Field(default=None, alias="createdDateTime")
    created_by: Optional[StrictStr] = Field(default=None, alias="createdBy")
    last_modified_date_time: Optional[StrictStr] = Field(default=None, alias="lastModifiedDateTime")
    last_modified_by: Optional[StrictStr] = Field(default=None, alias="lastModifiedBy")
    deleted_by: Optional[StrictStr] = Field(default=None, alias="deletedBy")
    deleted_date_time: Optional[StrictStr] = Field(default=None, alias="deletedDateTime")
    is_deleted: Optional[StrictBool] = Field(default=None, alias="isDeleted")
    __properties: ClassVar[List[str]] = ["tenantId", "tenantTypes", "organizationIdentifier", "organizationName", "createdDateTime", "createdBy", "lastModifiedDateTime", "lastModifiedBy", "deletedBy", "deletedDateTime", "isDeleted"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TenantApiPartnershipV1ParternshipTenantResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "tenant_types",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if tenant_id (nullable) is None
        # and model_fields_set contains the field
        if self.tenant_id is None and "tenant_id" in self.model_fields_set:
            _dict['tenantId'] = None

        # set to None if tenant_types (nullable) is None
        # and model_fields_set contains the field
        if self.tenant_types is None and "tenant_types" in self.model_fields_set:
            _dict['tenantTypes'] = None

        # set to None if organization_identifier (nullable) is None
        # and model_fields_set contains the field
        if self.organization_identifier is None and "organization_identifier" in self.model_fields_set:
            _dict['organizationIdentifier'] = None

        # set to None if organization_name (nullable) is None
        # and model_fields_set contains the field
        if self.organization_name is None and "organization_name" in self.model_fields_set:
            _dict['organizationName'] = None

        # set to None if created_date_time (nullable) is None
        # and model_fields_set contains the field
        if self.created_date_time is None and "created_date_time" in self.model_fields_set:
            _dict['createdDateTime'] = None

        # set to None if created_by (nullable) is None
        # and model_fields_set contains the field
        if self.created_by is None and "created_by" in self.model_fields_set:
            _dict['createdBy'] = None

        # set to None if last_modified_date_time (nullable) is None
        # and model_fields_set contains the field
        if self.last_modified_date_time is None and "last_modified_date_time" in self.model_fields_set:
            _dict['lastModifiedDateTime'] = None

        # set to None if last_modified_by (nullable) is None
        # and model_fields_set contains the field
        if self.last_modified_by is None and "last_modified_by" in self.model_fields_set:
            _dict['lastModifiedBy'] = None

        # set to None if deleted_by (nullable) is None
        # and model_fields_set contains the field
        if self.deleted_by is None and "deleted_by" in self.model_fields_set:
            _dict['deletedBy'] = None

        # set to None if deleted_date_time (nullable) is None
        # and model_fields_set contains the field
        if self.deleted_date_time is None and "deleted_date_time" in self.model_fields_set:
            _dict['deletedDateTime'] = None

        # set to None if is_deleted (nullable) is None
        # and model_fields_set contains the field
        if self.is_deleted is None and "is_deleted" in self.model_fields_set:
            _dict['isDeleted'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TenantApiPartnershipV1ParternshipTenantResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tenantId": obj.get("tenantId"),
            "tenantTypes": obj.get("tenantTypes"),
            "organizationIdentifier": obj.get("organizationIdentifier"),
            "organizationName": obj.get("organizationName"),
            "createdDateTime": obj.get("createdDateTime"),
            "createdBy": obj.get("createdBy"),
            "lastModifiedDateTime": obj.get("lastModifiedDateTime"),
            "lastModifiedBy": obj.get("lastModifiedBy"),
            "deletedBy": obj.get("deletedBy"),
            "deletedDateTime": obj.get("deletedDateTime"),
            "isDeleted": obj.get("isDeleted")
        })
        return _obj


