# coding: utf-8

"""
    Tenant Api

    Tenant Api - v1.0

    The version of the OpenAPI document: v1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TenantApiPartnershipV1PartnershipSyncDirection(str, Enum):
    """
    TenantApiPartnershipV1PartnershipSyncDirection
    """

    """
    allowed enum values
    """
    UNKNOWN = 'Unknown'
    INBOUND = 'Inbound'
    OUTBOUND = 'Outbound'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TenantApiPartnershipV1PartnershipSyncDirection from a JSON string"""
        return cls(json.loads(json_str))


